// Code generated by protoc-gen-go. DO NOT EDIT.
// source: matrix_io/recognition/v1/recognition_service.proto

package recognitionServiceV1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/matrix-io/matrix-protos-go/matrix_io/vision/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Message used when calling StoreDescriptors()
type StoreFeatureDescriptorsRequest struct {
	// Source images / video to obtain descriptors
	VisionRequest *v1.VisionRequest `protobuf:"bytes,1,opt,name=vision_request,json=visionRequest,proto3" json:"vision_request,omitempty"`
	// Arbitrary tags to use for descriptors calculated from
	// vision_request. Ignored when feature_descriptors are set.
	// ie ['ruben', 'godoy family']
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	// Set of descriptors
	FeatureDescriptors []*FeatureDescriptor `protobuf:"bytes,3,rep,name=feature_descriptors,json=featureDescriptors,proto3" json:"feature_descriptors,omitempty"`
	// Optional device IDs to associate the descriptor
	// with a set of devices
	DeviceId             []string `protobuf:"bytes,4,rep,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreFeatureDescriptorsRequest) Reset()         { *m = StoreFeatureDescriptorsRequest{} }
func (m *StoreFeatureDescriptorsRequest) String() string { return proto.CompactTextString(m) }
func (*StoreFeatureDescriptorsRequest) ProtoMessage()    {}
func (*StoreFeatureDescriptorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{0}
}

func (m *StoreFeatureDescriptorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreFeatureDescriptorsRequest.Unmarshal(m, b)
}
func (m *StoreFeatureDescriptorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreFeatureDescriptorsRequest.Marshal(b, m, deterministic)
}
func (m *StoreFeatureDescriptorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreFeatureDescriptorsRequest.Merge(m, src)
}
func (m *StoreFeatureDescriptorsRequest) XXX_Size() int {
	return xxx_messageInfo_StoreFeatureDescriptorsRequest.Size(m)
}
func (m *StoreFeatureDescriptorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreFeatureDescriptorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreFeatureDescriptorsRequest proto.InternalMessageInfo

func (m *StoreFeatureDescriptorsRequest) GetVisionRequest() *v1.VisionRequest {
	if m != nil {
		return m.VisionRequest
	}
	return nil
}

func (m *StoreFeatureDescriptorsRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StoreFeatureDescriptorsRequest) GetFeatureDescriptors() []*FeatureDescriptor {
	if m != nil {
		return m.FeatureDescriptors
	}
	return nil
}

func (m *StoreFeatureDescriptorsRequest) GetDeviceId() []string {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

// Message returned by StoreDescriptors()
type StoreFeatureDescriptorsResponse struct {
	// Stored descriptor IDS
	Uuids                []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreFeatureDescriptorsResponse) Reset()         { *m = StoreFeatureDescriptorsResponse{} }
func (m *StoreFeatureDescriptorsResponse) String() string { return proto.CompactTextString(m) }
func (*StoreFeatureDescriptorsResponse) ProtoMessage()    {}
func (*StoreFeatureDescriptorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{1}
}

func (m *StoreFeatureDescriptorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreFeatureDescriptorsResponse.Unmarshal(m, b)
}
func (m *StoreFeatureDescriptorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreFeatureDescriptorsResponse.Marshal(b, m, deterministic)
}
func (m *StoreFeatureDescriptorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreFeatureDescriptorsResponse.Merge(m, src)
}
func (m *StoreFeatureDescriptorsResponse) XXX_Size() int {
	return xxx_messageInfo_StoreFeatureDescriptorsResponse.Size(m)
}
func (m *StoreFeatureDescriptorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreFeatureDescriptorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreFeatureDescriptorsResponse proto.InternalMessageInfo

func (m *StoreFeatureDescriptorsResponse) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

// Message used when calling GetDescriptors()
type GetFeatureDescriptorsRequest struct {
	// Specific descriptor uuids to obtain
	Uuids []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	// Specific tags to obtain. Ignored when uuids is defined.
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	// Device ID to get descriptors for
	DeviceId string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Next page token when paginating
	NextPageToken        string   `protobuf:"bytes,4,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeatureDescriptorsRequest) Reset()         { *m = GetFeatureDescriptorsRequest{} }
func (m *GetFeatureDescriptorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeatureDescriptorsRequest) ProtoMessage()    {}
func (*GetFeatureDescriptorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{2}
}

func (m *GetFeatureDescriptorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeatureDescriptorsRequest.Unmarshal(m, b)
}
func (m *GetFeatureDescriptorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeatureDescriptorsRequest.Marshal(b, m, deterministic)
}
func (m *GetFeatureDescriptorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeatureDescriptorsRequest.Merge(m, src)
}
func (m *GetFeatureDescriptorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeatureDescriptorsRequest.Size(m)
}
func (m *GetFeatureDescriptorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeatureDescriptorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeatureDescriptorsRequest proto.InternalMessageInfo

func (m *GetFeatureDescriptorsRequest) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *GetFeatureDescriptorsRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetFeatureDescriptorsRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *GetFeatureDescriptorsRequest) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Message returned by GetFeatureDescriptors()
type GetFeatureDescriptorsResponse struct {
	// Set of descriptors
	FeatureDescriptorList *FeatureDescriptorList `protobuf:"bytes,1,opt,name=feature_descriptor_list,json=featureDescriptorList,proto3" json:"feature_descriptor_list,omitempty"`
	// Token use for pagination when there are too many results
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeatureDescriptorsResponse) Reset()         { *m = GetFeatureDescriptorsResponse{} }
func (m *GetFeatureDescriptorsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeatureDescriptorsResponse) ProtoMessage()    {}
func (*GetFeatureDescriptorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{3}
}

func (m *GetFeatureDescriptorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeatureDescriptorsResponse.Unmarshal(m, b)
}
func (m *GetFeatureDescriptorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeatureDescriptorsResponse.Marshal(b, m, deterministic)
}
func (m *GetFeatureDescriptorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeatureDescriptorsResponse.Merge(m, src)
}
func (m *GetFeatureDescriptorsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeatureDescriptorsResponse.Size(m)
}
func (m *GetFeatureDescriptorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeatureDescriptorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeatureDescriptorsResponse proto.InternalMessageInfo

func (m *GetFeatureDescriptorsResponse) GetFeatureDescriptorList() *FeatureDescriptorList {
	if m != nil {
		return m.FeatureDescriptorList
	}
	return nil
}

func (m *GetFeatureDescriptorsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

// Message used when calling DeleteFeatureDescriptors()
type DeleteFeatureDescriptorsRequest struct {
	// Stored descriptor IDs to delete
	Uuids []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	// Delete descriptors by tags, delete ALL descriptors
	// matching given tags. Ignored when uuid is set.
	Tags                 []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFeatureDescriptorsRequest) Reset()         { *m = DeleteFeatureDescriptorsRequest{} }
func (m *DeleteFeatureDescriptorsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFeatureDescriptorsRequest) ProtoMessage()    {}
func (*DeleteFeatureDescriptorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{4}
}

func (m *DeleteFeatureDescriptorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeatureDescriptorsRequest.Unmarshal(m, b)
}
func (m *DeleteFeatureDescriptorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeatureDescriptorsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFeatureDescriptorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeatureDescriptorsRequest.Merge(m, src)
}
func (m *DeleteFeatureDescriptorsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFeatureDescriptorsRequest.Size(m)
}
func (m *DeleteFeatureDescriptorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeatureDescriptorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeatureDescriptorsRequest proto.InternalMessageInfo

func (m *DeleteFeatureDescriptorsRequest) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *DeleteFeatureDescriptorsRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// Message returned by DeleteDescriptors()
type DeleteFeatureDescriptorsResponse struct {
	// UUIDs of deleted descriptors
	Uuids                []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFeatureDescriptorsResponse) Reset()         { *m = DeleteFeatureDescriptorsResponse{} }
func (m *DeleteFeatureDescriptorsResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFeatureDescriptorsResponse) ProtoMessage()    {}
func (*DeleteFeatureDescriptorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{5}
}

func (m *DeleteFeatureDescriptorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeatureDescriptorsResponse.Unmarshal(m, b)
}
func (m *DeleteFeatureDescriptorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeatureDescriptorsResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFeatureDescriptorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeatureDescriptorsResponse.Merge(m, src)
}
func (m *DeleteFeatureDescriptorsResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFeatureDescriptorsResponse.Size(m)
}
func (m *DeleteFeatureDescriptorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeatureDescriptorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeatureDescriptorsResponse proto.InternalMessageInfo

func (m *DeleteFeatureDescriptorsResponse) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

// Message used when calling Recognize()
type RecognizeRequest struct {
	// Source for VisionRequest for recognition
	VisionRequest *v1.VisionRequest `protobuf:"bytes,1,opt,name=vision_request,json=visionRequest,proto3" json:"vision_request,omitempty"`
	// Set of descriptors
	FeatureDescriptorList *FeatureDescriptorList `protobuf:"bytes,2,opt,name=feature_descriptor_list,json=featureDescriptorList,proto3" json:"feature_descriptor_list,omitempty"`
	// Signals the desired algorithm for recognitions
	MatchingAlgorithmVersion string   `protobuf:"bytes,3,opt,name=matching_algorithm_version,json=matchingAlgorithmVersion,proto3" json:"matching_algorithm_version,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RecognizeRequest) Reset()         { *m = RecognizeRequest{} }
func (m *RecognizeRequest) String() string { return proto.CompactTextString(m) }
func (*RecognizeRequest) ProtoMessage()    {}
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{6}
}

func (m *RecognizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognizeRequest.Unmarshal(m, b)
}
func (m *RecognizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognizeRequest.Marshal(b, m, deterministic)
}
func (m *RecognizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognizeRequest.Merge(m, src)
}
func (m *RecognizeRequest) XXX_Size() int {
	return xxx_messageInfo_RecognizeRequest.Size(m)
}
func (m *RecognizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecognizeRequest proto.InternalMessageInfo

func (m *RecognizeRequest) GetVisionRequest() *v1.VisionRequest {
	if m != nil {
		return m.VisionRequest
	}
	return nil
}

func (m *RecognizeRequest) GetFeatureDescriptorList() *FeatureDescriptorList {
	if m != nil {
		return m.FeatureDescriptorList
	}
	return nil
}

func (m *RecognizeRequest) GetMatchingAlgorithmVersion() string {
	if m != nil {
		return m.MatchingAlgorithmVersion
	}
	return ""
}

// Message describes a descriptor match
type FeatureDescriptorMatch struct {
	// user set tags
	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// Score for the match from 0 to 1.
	// A smaller value means a closer match.
	// Statistical interpretation of the scores makes no sense with this value.
	Score                float32  `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureDescriptorMatch) Reset()         { *m = FeatureDescriptorMatch{} }
func (m *FeatureDescriptorMatch) String() string { return proto.CompactTextString(m) }
func (*FeatureDescriptorMatch) ProtoMessage()    {}
func (*FeatureDescriptorMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{7}
}

func (m *FeatureDescriptorMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureDescriptorMatch.Unmarshal(m, b)
}
func (m *FeatureDescriptorMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureDescriptorMatch.Marshal(b, m, deterministic)
}
func (m *FeatureDescriptorMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureDescriptorMatch.Merge(m, src)
}
func (m *FeatureDescriptorMatch) XXX_Size() int {
	return xxx_messageInfo_FeatureDescriptorMatch.Size(m)
}
func (m *FeatureDescriptorMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureDescriptorMatch.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureDescriptorMatch proto.InternalMessageInfo

func (m *FeatureDescriptorMatch) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *FeatureDescriptorMatch) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

// Message returned by Recognize()
type RecognizeResponse struct {
	// List of matches
	Matches              []*FeatureDescriptorMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *RecognizeResponse) Reset()         { *m = RecognizeResponse{} }
func (m *RecognizeResponse) String() string { return proto.CompactTextString(m) }
func (*RecognizeResponse) ProtoMessage()    {}
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{8}
}

func (m *RecognizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognizeResponse.Unmarshal(m, b)
}
func (m *RecognizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognizeResponse.Marshal(b, m, deterministic)
}
func (m *RecognizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognizeResponse.Merge(m, src)
}
func (m *RecognizeResponse) XXX_Size() int {
	return xxx_messageInfo_RecognizeResponse.Size(m)
}
func (m *RecognizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecognizeResponse proto.InternalMessageInfo

func (m *RecognizeResponse) GetMatches() []*FeatureDescriptorMatch {
	if m != nil {
		return m.Matches
	}
	return nil
}

// Message used when calling GetFeatureDescriptorTags()
type GetFeatureDescriptorTagsRequest struct {
	// Device IDs to get descriptors tags for
	DeviceId             []string `protobuf:"bytes,1,rep,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeatureDescriptorTagsRequest) Reset()         { *m = GetFeatureDescriptorTagsRequest{} }
func (m *GetFeatureDescriptorTagsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeatureDescriptorTagsRequest) ProtoMessage()    {}
func (*GetFeatureDescriptorTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{9}
}

func (m *GetFeatureDescriptorTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeatureDescriptorTagsRequest.Unmarshal(m, b)
}
func (m *GetFeatureDescriptorTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeatureDescriptorTagsRequest.Marshal(b, m, deterministic)
}
func (m *GetFeatureDescriptorTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeatureDescriptorTagsRequest.Merge(m, src)
}
func (m *GetFeatureDescriptorTagsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeatureDescriptorTagsRequest.Size(m)
}
func (m *GetFeatureDescriptorTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeatureDescriptorTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeatureDescriptorTagsRequest proto.InternalMessageInfo

func (m *GetFeatureDescriptorTagsRequest) GetDeviceId() []string {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

// Groups tags per device, so client apps can
// pull all tags and then present which tags
// are only registered under a specific device
type FeatureDescriptorTagsForDevice struct {
	// Available descriptor tags
	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// If set, the above tags are only available in such device id
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureDescriptorTagsForDevice) Reset()         { *m = FeatureDescriptorTagsForDevice{} }
func (m *FeatureDescriptorTagsForDevice) String() string { return proto.CompactTextString(m) }
func (*FeatureDescriptorTagsForDevice) ProtoMessage()    {}
func (*FeatureDescriptorTagsForDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{10}
}

func (m *FeatureDescriptorTagsForDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureDescriptorTagsForDevice.Unmarshal(m, b)
}
func (m *FeatureDescriptorTagsForDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureDescriptorTagsForDevice.Marshal(b, m, deterministic)
}
func (m *FeatureDescriptorTagsForDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureDescriptorTagsForDevice.Merge(m, src)
}
func (m *FeatureDescriptorTagsForDevice) XXX_Size() int {
	return xxx_messageInfo_FeatureDescriptorTagsForDevice.Size(m)
}
func (m *FeatureDescriptorTagsForDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureDescriptorTagsForDevice.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureDescriptorTagsForDevice proto.InternalMessageInfo

func (m *FeatureDescriptorTagsForDevice) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *FeatureDescriptorTagsForDevice) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

// Message returned by GetFeatureDescriptorTags()
type GetFeatureDescriptorTagsResponse struct {
	// Device ID to get descriptors tags for
	FeatureTagsForDevice []*FeatureDescriptorTagsForDevice `protobuf:"bytes,1,rep,name=feature_tags_for_device,json=featureTagsForDevice,proto3" json:"feature_tags_for_device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetFeatureDescriptorTagsResponse) Reset()         { *m = GetFeatureDescriptorTagsResponse{} }
func (m *GetFeatureDescriptorTagsResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeatureDescriptorTagsResponse) ProtoMessage()    {}
func (*GetFeatureDescriptorTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f056f46eff0fcd7, []int{11}
}

func (m *GetFeatureDescriptorTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeatureDescriptorTagsResponse.Unmarshal(m, b)
}
func (m *GetFeatureDescriptorTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeatureDescriptorTagsResponse.Marshal(b, m, deterministic)
}
func (m *GetFeatureDescriptorTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeatureDescriptorTagsResponse.Merge(m, src)
}
func (m *GetFeatureDescriptorTagsResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeatureDescriptorTagsResponse.Size(m)
}
func (m *GetFeatureDescriptorTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeatureDescriptorTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeatureDescriptorTagsResponse proto.InternalMessageInfo

func (m *GetFeatureDescriptorTagsResponse) GetFeatureTagsForDevice() []*FeatureDescriptorTagsForDevice {
	if m != nil {
		return m.FeatureTagsForDevice
	}
	return nil
}

func init() {
	proto.RegisterType((*StoreFeatureDescriptorsRequest)(nil), "matrix_io.recognition.v1.StoreFeatureDescriptorsRequest")
	proto.RegisterType((*StoreFeatureDescriptorsResponse)(nil), "matrix_io.recognition.v1.StoreFeatureDescriptorsResponse")
	proto.RegisterType((*GetFeatureDescriptorsRequest)(nil), "matrix_io.recognition.v1.GetFeatureDescriptorsRequest")
	proto.RegisterType((*GetFeatureDescriptorsResponse)(nil), "matrix_io.recognition.v1.GetFeatureDescriptorsResponse")
	proto.RegisterType((*DeleteFeatureDescriptorsRequest)(nil), "matrix_io.recognition.v1.DeleteFeatureDescriptorsRequest")
	proto.RegisterType((*DeleteFeatureDescriptorsResponse)(nil), "matrix_io.recognition.v1.DeleteFeatureDescriptorsResponse")
	proto.RegisterType((*RecognizeRequest)(nil), "matrix_io.recognition.v1.RecognizeRequest")
	proto.RegisterType((*FeatureDescriptorMatch)(nil), "matrix_io.recognition.v1.FeatureDescriptorMatch")
	proto.RegisterType((*RecognizeResponse)(nil), "matrix_io.recognition.v1.RecognizeResponse")
	proto.RegisterType((*GetFeatureDescriptorTagsRequest)(nil), "matrix_io.recognition.v1.GetFeatureDescriptorTagsRequest")
	proto.RegisterType((*FeatureDescriptorTagsForDevice)(nil), "matrix_io.recognition.v1.FeatureDescriptorTagsForDevice")
	proto.RegisterType((*GetFeatureDescriptorTagsResponse)(nil), "matrix_io.recognition.v1.GetFeatureDescriptorTagsResponse")
}

func init() {
	proto.RegisterFile("matrix_io/recognition/v1/recognition_service.proto", fileDescriptor_3f056f46eff0fcd7)
}

var fileDescriptor_3f056f46eff0fcd7 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5d, 0x6b, 0xd4, 0x4c,
	0x14, 0xee, 0x64, 0xdb, 0xf7, 0xb5, 0xa7, 0xd4, 0x8f, 0xb1, 0x75, 0x43, 0xd4, 0x76, 0xcd, 0x85,
	0x2c, 0x2d, 0xcd, 0xba, 0x2b, 0xd8, 0xfa, 0x81, 0x60, 0x29, 0x95, 0xaa, 0xc5, 0x9a, 0x96, 0xbd,
	0x10, 0x21, 0xa4, 0xbb, 0xb3, 0xe9, 0x60, 0x37, 0xb3, 0x4e, 0x66, 0x43, 0xf1, 0xda, 0x2b, 0x41,
	0x10, 0xfa, 0x2f, 0x04, 0xc1, 0x9f, 0xe1, 0x6f, 0xf2, 0x4a, 0x92, 0xc9, 0xee, 0x26, 0xcd, 0xc7,
	0x76, 0x4b, 0xbd, 0x9b, 0x39, 0x79, 0xce, 0x73, 0x9e, 0xf3, 0xe4, 0xcc, 0x24, 0xd0, 0xe8, 0xda,
	0x82, 0xd3, 0x13, 0x8b, 0xb2, 0x1a, 0x27, 0x2d, 0xe6, 0xb8, 0x54, 0x50, 0xe6, 0xd6, 0xfc, 0x7a,
	0x7c, 0x6b, 0x79, 0x84, 0xfb, 0xb4, 0x45, 0x8c, 0x1e, 0x67, 0x82, 0x61, 0x75, 0x98, 0x63, 0xc4,
	0x40, 0x86, 0x5f, 0xd7, 0xaa, 0x23, 0x36, 0x9f, 0x7a, 0x11, 0x91, 0x5c, 0x25, 0x39, 0xb4, 0x95,
	0xf3, 0xd4, 0x95, 0x58, 0xfd, 0x0f, 0x82, 0xa5, 0x7d, 0xc1, 0x38, 0xd9, 0x26, 0xb6, 0xe8, 0x73,
	0xb2, 0x45, 0xbc, 0x16, 0xa7, 0x3d, 0xc1, 0xb8, 0x67, 0x92, 0x4f, 0x7d, 0xe2, 0x09, 0xbc, 0x03,
	0x57, 0xa3, 0x32, 0x5c, 0x46, 0x54, 0x54, 0x41, 0xd5, 0xb9, 0x86, 0x6e, 0x8c, 0xb4, 0x4a, 0x80,
	0xe1, 0xd7, 0x8d, 0x66, 0xb8, 0x8a, 0x72, 0xcd, 0x79, 0x3f, 0xbe, 0xc5, 0x18, 0xa6, 0x85, 0xed,
	0x78, 0xaa, 0x52, 0x29, 0x55, 0x67, 0xcd, 0x70, 0x8d, 0x3f, 0xc0, 0xcd, 0x8e, 0xac, 0x6d, 0xb5,
	0x47, 0xc5, 0xd5, 0x52, 0xa5, 0x54, 0x9d, 0x6b, 0xac, 0x1a, 0x79, 0x7e, 0x18, 0x29, 0xc1, 0x26,
	0xee, 0xa4, 0x7a, 0xc0, 0xb7, 0x61, 0xb6, 0x4d, 0x02, 0x6f, 0x2c, 0xda, 0x56, 0xa7, 0xc3, 0xb2,
	0x57, 0x64, 0x60, 0xa7, 0xad, 0xaf, 0xc3, 0x72, 0x6e, 0xef, 0x5e, 0x8f, 0xb9, 0x1e, 0xc1, 0x0b,
	0x30, 0xd3, 0xef, 0xd3, 0xb6, 0xa7, 0xa2, 0x30, 0x57, 0x6e, 0xf4, 0x6f, 0x08, 0xee, 0xbc, 0x24,
	0x22, 0xdf, 0xb3, 0xcc, 0xb4, 0xcc, 0xf6, 0x13, 0x02, 0x4b, 0x15, 0x14, 0x17, 0x88, 0xef, 0xc3,
	0x35, 0x97, 0x9c, 0x08, 0xab, 0x67, 0x3b, 0xc4, 0x12, 0xec, 0x23, 0x71, 0xd5, 0xe9, 0x10, 0x32,
	0x1f, 0x84, 0xf7, 0x6c, 0x87, 0x1c, 0x04, 0x41, 0xfd, 0x17, 0x82, 0xbb, 0x39, 0x7a, 0xa2, 0x3e,
	0x1c, 0x28, 0xa7, 0x5d, 0xb6, 0x8e, 0xe9, 0xf0, 0x6d, 0xd6, 0x26, 0x70, 0xfa, 0x0d, 0xf5, 0x84,
	0xb9, 0xd8, 0xc9, 0x0a, 0x67, 0x49, 0x56, 0xb2, 0x24, 0xbf, 0x86, 0xe5, 0x2d, 0x72, 0x4c, 0x04,
	0xb9, 0x04, 0x13, 0xf5, 0x0d, 0xa8, 0xe4, 0x93, 0x15, 0xbe, 0xc9, 0x2f, 0x0a, 0x5c, 0x37, 0x65,
	0xbb, 0x9f, 0xc9, 0x3f, 0x98, 0xf8, 0x02, 0xdf, 0x95, 0x4b, 0xf5, 0xfd, 0x19, 0x68, 0x5d, 0x5b,
	0xb4, 0x8e, 0xa8, 0xeb, 0x58, 0xf6, 0xb1, 0xc3, 0x38, 0x15, 0x47, 0x5d, 0xcb, 0x27, 0x3c, 0x50,
	0x13, 0x0d, 0x96, 0x3a, 0x40, 0xbc, 0x18, 0x00, 0x9a, 0xf2, 0xb9, 0xbe, 0x09, 0xb7, 0x52, 0xd5,
	0x76, 0x03, 0xf0, 0xd0, 0x6e, 0x14, 0x9b, 0xd9, 0x05, 0x98, 0xf1, 0x5a, 0x8c, 0x93, 0xb0, 0x05,
	0xc5, 0x94, 0x1b, 0xdd, 0x82, 0x1b, 0x31, 0x27, 0x23, 0xd7, 0x5f, 0xc1, 0xff, 0x61, 0x51, 0x22,
	0x19, 0xe6, 0x1a, 0x0f, 0x26, 0xe8, 0x37, 0x54, 0x60, 0x0e, 0x08, 0xf4, 0xe7, 0xb0, 0x9c, 0x35,
	0xe4, 0x07, 0xb6, 0x33, 0x1c, 0x99, 0xc4, 0x69, 0x42, 0x67, 0x8e, 0xfb, 0x3b, 0x58, 0xca, 0x4c,
	0xde, 0x66, 0x7c, 0x2b, 0xc4, 0x64, 0x36, 0x9b, 0xa0, 0x54, 0x92, 0x07, 0x54, 0x3f, 0x45, 0x50,
	0xc9, 0xd7, 0x14, 0x79, 0xc0, 0x46, 0x33, 0x10, 0x30, 0x5a, 0x1d, 0xc6, 0x2d, 0xc9, 0x10, 0x79,
	0xb2, 0x31, 0x81, 0x27, 0x09, 0xc1, 0xe6, 0x42, 0x44, 0x9c, 0x88, 0x36, 0x7e, 0xcf, 0x00, 0x36,
	0x47, 0x3c, 0xfb, 0xf2, 0xeb, 0x80, 0xbf, 0x23, 0x28, 0xe7, 0xdc, 0x77, 0xb8, 0x40, 0x42, 0xf1,
	0xe7, 0x41, 0x7b, 0x7c, 0x81, 0x4c, 0x69, 0x8c, 0x3e, 0x85, 0xbf, 0x22, 0x58, 0xcc, 0xbc, 0xb8,
	0xf0, 0xa3, 0x7c, 0xda, 0xa2, 0x9b, 0x57, 0x5b, 0x9f, 0x38, 0x6f, 0x28, 0xe6, 0x14, 0x81, 0x9a,
	0x77, 0x8d, 0xe0, 0x82, 0x36, 0xc7, 0xdc, 0x63, 0xda, 0x93, 0x8b, 0xa4, 0x26, 0x54, 0xe5, 0x8d,
	0x58, 0x91, 0xaa, 0x31, 0x47, 0xa5, 0x48, 0xd5, 0xb8, 0x89, 0xd6, 0xa7, 0x70, 0x07, 0x66, 0x87,
	0x87, 0x1d, 0xaf, 0xe4, 0x53, 0x9d, 0xbd, 0x5b, 0xb5, 0xd5, 0x73, 0x61, 0x07, 0x75, 0x36, 0x7f,
	0x22, 0xb8, 0xc7, 0x5c, 0x12, 0x25, 0x51, 0x26, 0x7f, 0x5b, 0xce, 0x64, 0x6e, 0x96, 0xd3, 0xd3,
	0xbe, 0x17, 0xe0, 0xf6, 0xd0, 0xfb, 0x7d, 0x87, 0x8a, 0xa3, 0xfe, 0xa1, 0xd1, 0x62, 0xdd, 0x9a,
	0x24, 0x59, 0xa3, 0x6c, 0xb0, 0x0a, 0xc9, 0xbc, 0x35, 0x67, 0x10, 0x48, 0xff, 0x32, 0x3d, 0xe5,
	0x29, 0xe6, 0x66, 0xfd, 0x87, 0x52, 0xde, 0x0d, 0xf1, 0x3b, 0x6f, 0x8d, 0x58, 0x65, 0xa3, 0x59,
	0x3f, 0xfc, 0x2f, 0xa4, 0x7c, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xde, 0x2d, 0xbb, 0xfc,
	0x09, 0x00, 0x00,
}
