// Code generated by protoc-gen-go. DO NOT EDIT.
// source: matrix_io/malos/v1/comm.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Zigbee command types definition
type ZigBeeMsg_ZigBeeCmdType int32

const (
	ZigBeeMsg_ZCL          ZigBeeMsg_ZigBeeCmdType = 0
	ZigBeeMsg_NETWORK_MGMT ZigBeeMsg_ZigBeeCmdType = 1
)

var ZigBeeMsg_ZigBeeCmdType_name = map[int32]string{
	0: "ZCL",
	1: "NETWORK_MGMT",
}

var ZigBeeMsg_ZigBeeCmdType_value = map[string]int32{
	"ZCL":          0,
	"NETWORK_MGMT": 1,
}

func (x ZigBeeMsg_ZigBeeCmdType) String() string {
	return proto.EnumName(ZigBeeMsg_ZigBeeCmdType_name, int32(x))
}

func (ZigBeeMsg_ZigBeeCmdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0}
}

// ZCL commands type
type ZigBeeMsg_ZCLCmd_ZCLCmdType int32

const (
	ZigBeeMsg_ZCLCmd_ON_OFF        ZigBeeMsg_ZCLCmd_ZCLCmdType = 0
	ZigBeeMsg_ZCLCmd_LEVEL         ZigBeeMsg_ZCLCmd_ZCLCmdType = 1
	ZigBeeMsg_ZCLCmd_COLOR_CONTROL ZigBeeMsg_ZCLCmd_ZCLCmdType = 2
	ZigBeeMsg_ZCLCmd_IDENTIFY      ZigBeeMsg_ZCLCmd_ZCLCmdType = 3
)

var ZigBeeMsg_ZCLCmd_ZCLCmdType_name = map[int32]string{
	0: "ON_OFF",
	1: "LEVEL",
	2: "COLOR_CONTROL",
	3: "IDENTIFY",
}

var ZigBeeMsg_ZCLCmd_ZCLCmdType_value = map[string]int32{
	"ON_OFF":        0,
	"LEVEL":         1,
	"COLOR_CONTROL": 2,
	"IDENTIFY":      3,
}

func (x ZigBeeMsg_ZCLCmd_ZCLCmdType) String() string {
	return proto.EnumName(ZigBeeMsg_ZCLCmd_ZCLCmdType_name, int32(x))
}

func (ZigBeeMsg_ZCLCmd_ZCLCmdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 0}
}

type ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType int32

const (
	ZigBeeMsg_ZCLCmd_OnOffCmd_ON     ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType = 0
	ZigBeeMsg_ZCLCmd_OnOffCmd_OFF    ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType = 1
	ZigBeeMsg_ZCLCmd_OnOffCmd_TOGGLE ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType = 2
)

var ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType_name = map[int32]string{
	0: "ON",
	1: "OFF",
	2: "TOGGLE",
}

var ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType_value = map[string]int32{
	"ON":     0,
	"OFF":    1,
	"TOGGLE": 2,
}

func (x ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType) String() string {
	return proto.EnumName(ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType_name, int32(x))
}

func (ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 0, 0}
}

// ZCL Level commands types
type ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType int32

const (
	ZigBeeMsg_ZCLCmd_LevelCmd_MOVE_TO_LEVEL ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType = 0
	ZigBeeMsg_ZCLCmd_LevelCmd_MOVE          ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType = 1
)

var ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType_name = map[int32]string{
	0: "MOVE_TO_LEVEL",
	1: "MOVE",
}

var ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType_value = map[string]int32{
	"MOVE_TO_LEVEL": 0,
	"MOVE":          1,
}

func (x ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType) String() string {
	return proto.EnumName(ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType_name, int32(x))
}

func (ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 1, 0}
}

// ZCL ColorControl command types
type ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType int32

const (
	ZigBeeMsg_ZCLCmd_ColorControlCmd_MOVETOHUE       ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType = 0
	ZigBeeMsg_ZCLCmd_ColorControlCmd_MOVETOSAT       ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType = 1
	ZigBeeMsg_ZCLCmd_ColorControlCmd_MOVETOHUEANDSAT ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType = 2
	ZigBeeMsg_ZCLCmd_ColorControlCmd_MOVETOCOLORTEMP ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType = 3
)

var ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType_name = map[int32]string{
	0: "MOVETOHUE",
	1: "MOVETOSAT",
	2: "MOVETOHUEANDSAT",
	3: "MOVETOCOLORTEMP",
}

var ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType_value = map[string]int32{
	"MOVETOHUE":       0,
	"MOVETOSAT":       1,
	"MOVETOHUEANDSAT": 2,
	"MOVETOCOLORTEMP": 3,
}

func (x ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType) String() string {
	return proto.EnumName(ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType_name, int32(x))
}

func (ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 2, 0}
}

// Values of the Direction Param
type ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam int32

const (
	ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_SHORTEST_DISTANCE ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam = 0
	ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_LONGEST_DISTANCE  ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam = 1
	ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_UP                ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam = 2
	ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DOWN              ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam = 3
)

var ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam_name = map[int32]string{
	0: "SHORTEST_DISTANCE",
	1: "LONGEST_DISTANCE",
	2: "UP",
	3: "DOWN",
}

var ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam_value = map[string]int32{
	"SHORTEST_DISTANCE": 0,
	"LONGEST_DISTANCE":  1,
	"UP":                2,
	"DOWN":              3,
}

func (x ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam) String() string {
	return proto.EnumName(ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam_name, int32(x))
}

func (ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 2, 0, 0}
}

type ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType int32

const (
	// Starts the identification process
	ZigBeeMsg_ZCLCmd_IdentifyCmd_IDENTIFY_ON ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType = 0
	// Stops the identification process
	ZigBeeMsg_ZCLCmd_IdentifyCmd_IDENTIFY_OFF ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType = 1
)

var ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType_name = map[int32]string{
	0: "IDENTIFY_ON",
	1: "IDENTIFY_OFF",
}

var ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType_value = map[string]int32{
	"IDENTIFY_ON":  0,
	"IDENTIFY_OFF": 1,
}

func (x ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType) String() string {
	return proto.EnumName(ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType_name, int32(x))
}

func (ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 3, 0}
}

// NetworkMgmt command types
type ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes int32

const (
	ZigBeeMsg_NetworkMgmtCmd_CREATE_NWK      ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes = 0
	ZigBeeMsg_NetworkMgmtCmd_LEAVE_NWK       ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes = 1
	ZigBeeMsg_NetworkMgmtCmd_NODE_LEAVE_NWK  ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes = 2
	ZigBeeMsg_NetworkMgmtCmd_PERMIT_JOIN     ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes = 3
	ZigBeeMsg_NetworkMgmtCmd_DISCOVERY_INFO  ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes = 4
	ZigBeeMsg_NetworkMgmtCmd_RESET_PROXY     ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes = 5
	ZigBeeMsg_NetworkMgmtCmd_IS_PROXY_ACTIVE ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes = 6
	ZigBeeMsg_NetworkMgmtCmd_NETWORK_STATUS  ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes = 7
)

var ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes_name = map[int32]string{
	0: "CREATE_NWK",
	1: "LEAVE_NWK",
	2: "NODE_LEAVE_NWK",
	3: "PERMIT_JOIN",
	4: "DISCOVERY_INFO",
	5: "RESET_PROXY",
	6: "IS_PROXY_ACTIVE",
	7: "NETWORK_STATUS",
}

var ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes_value = map[string]int32{
	"CREATE_NWK":      0,
	"LEAVE_NWK":       1,
	"NODE_LEAVE_NWK":  2,
	"PERMIT_JOIN":     3,
	"DISCOVERY_INFO":  4,
	"RESET_PROXY":     5,
	"IS_PROXY_ACTIVE": 6,
	"NETWORK_STATUS":  7,
}

func (x ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes) String() string {
	return proto.EnumName(ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes_name, int32(x))
}

func (ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 0}
}

type ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType int32

const (
	ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_SERVER_IN  ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType = 0
	ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_CLIENT_OUT ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType = 1
)

var ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType_name = map[int32]string{
	0: "SERVER_IN",
	1: "CLIENT_OUT",
}

var ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType_value = map[string]int32{
	"SERVER_IN":  0,
	"CLIENT_OUT": 1,
}

func (x ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType) String() string {
	return proto.EnumName(ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType_name, int32(x))
}

func (ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 2, 0}
}

type ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status int32

const (
	// * The node is not associated with a network in any way.
	ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_NO_NETWORK ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status = 0
	// * The node is currently attempting to join a network.
	ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_JOINING_NETWORK ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status = 1
	// The node is joined to a network.
	ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_JOINED_NETWORK ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status = 2
	// * The node is an end device joined to a network but its parent
	// is not responding.
	ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_JOINED_NETWORK_NO_PARENT ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status = 3
	// * The node is in the process of leaving its current network.
	ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_LEAVING_NETWORK ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status = 4
)

var ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status_name = map[int32]string{
	0: "NO_NETWORK",
	1: "JOINING_NETWORK",
	2: "JOINED_NETWORK",
	3: "JOINED_NETWORK_NO_PARENT",
	4: "LEAVING_NETWORK",
}

var ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status_value = map[string]int32{
	"NO_NETWORK":               0,
	"JOINING_NETWORK":          1,
	"JOINED_NETWORK":           2,
	"JOINED_NETWORK_NO_PARENT": 3,
	"LEAVING_NETWORK":          4,
}

func (x ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status) String() string {
	return proto.EnumName(ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status_name, int32(x))
}

func (ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 5, 0}
}

// ZWave Malos Opcodes
type ZWaveMsg_ZWaveOperations int32

const (
	ZWaveMsg_UNDEF      ZWaveMsg_ZWaveOperations = 0
	ZWaveMsg_SEND       ZWaveMsg_ZWaveOperations = 1
	ZWaveMsg_ADDNODE    ZWaveMsg_ZWaveOperations = 2
	ZWaveMsg_REMOVENODE ZWaveMsg_ZWaveOperations = 3
	ZWaveMsg_SETDEFAULT ZWaveMsg_ZWaveOperations = 4
	ZWaveMsg_LIST       ZWaveMsg_ZWaveOperations = 5
)

var ZWaveMsg_ZWaveOperations_name = map[int32]string{
	0: "UNDEF",
	1: "SEND",
	2: "ADDNODE",
	3: "REMOVENODE",
	4: "SETDEFAULT",
	5: "LIST",
}

var ZWaveMsg_ZWaveOperations_value = map[string]int32{
	"UNDEF":      0,
	"SEND":       1,
	"ADDNODE":    2,
	"REMOVENODE": 3,
	"SETDEFAULT": 4,
	"LIST":       5,
}

func (x ZWaveMsg_ZWaveOperations) String() string {
	return proto.EnumName(ZWaveMsg_ZWaveOperations_name, int32(x))
}

func (ZWaveMsg_ZWaveOperations) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{1, 0}
}

// ZigBee message
type ZigBeeMsg struct {
	// Zigbee command type
	Type ZigBeeMsg_ZigBeeCmdType `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_ZigBeeCmdType" json:"type,omitempty"`
	// ZigBee Cluster Library command
	ZclCmd *ZigBeeMsg_ZCLCmd `protobuf:"bytes,2,opt,name=zcl_cmd,json=zclCmd,proto3" json:"zcl_cmd,omitempty"`
	// Network management commnad
	NetworkMgmtCmd       *ZigBeeMsg_NetworkMgmtCmd `protobuf:"bytes,3,opt,name=network_mgmt_cmd,json=networkMgmtCmd,proto3" json:"network_mgmt_cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ZigBeeMsg) Reset()         { *m = ZigBeeMsg{} }
func (m *ZigBeeMsg) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg) ProtoMessage()    {}
func (*ZigBeeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0}
}

func (m *ZigBeeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg.Unmarshal(m, b)
}
func (m *ZigBeeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg.Merge(m, src)
}
func (m *ZigBeeMsg) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg.Size(m)
}
func (m *ZigBeeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg proto.InternalMessageInfo

func (m *ZigBeeMsg) GetType() ZigBeeMsg_ZigBeeCmdType {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_ZCL
}

func (m *ZigBeeMsg) GetZclCmd() *ZigBeeMsg_ZCLCmd {
	if m != nil {
		return m.ZclCmd
	}
	return nil
}

func (m *ZigBeeMsg) GetNetworkMgmtCmd() *ZigBeeMsg_NetworkMgmtCmd {
	if m != nil {
		return m.NetworkMgmtCmd
	}
	return nil
}

// ZigBee Cluster Library command definition
type ZigBeeMsg_ZCLCmd struct {
	// ZCL command type
	Type ZigBeeMsg_ZCLCmd_ZCLCmdType `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_ZCLCmdType" json:"type,omitempty"`
	// OnOff command
	OnoffCmd *ZigBeeMsg_ZCLCmd_OnOffCmd `protobuf:"bytes,2,opt,name=onoff_cmd,json=onoffCmd,proto3" json:"onoff_cmd,omitempty"`
	// Level command
	LevelCmd *ZigBeeMsg_ZCLCmd_LevelCmd `protobuf:"bytes,3,opt,name=level_cmd,json=levelCmd,proto3" json:"level_cmd,omitempty"`
	// Color control command
	ColorcontrolCmd *ZigBeeMsg_ZCLCmd_ColorControlCmd `protobuf:"bytes,4,opt,name=colorcontrol_cmd,json=colorcontrolCmd,proto3" json:"colorcontrol_cmd,omitempty"`
	// Identify command
	IdentifyCmd *ZigBeeMsg_ZCLCmd_IdentifyCmd `protobuf:"bytes,5,opt,name=identify_cmd,json=identifyCmd,proto3" json:"identify_cmd,omitempty"`
	// Node Id
	NodeId uint32 `protobuf:"varint,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Endpoint Id
	EndpointIndex        uint32   `protobuf:"varint,7,opt,name=endpoint_index,json=endpointIndex,proto3" json:"endpoint_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd) Reset()         { *m = ZigBeeMsg_ZCLCmd{} }
func (m *ZigBeeMsg_ZCLCmd) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_ZCLCmd) ProtoMessage()    {}
func (*ZigBeeMsg_ZCLCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0}
}

func (m *ZigBeeMsg_ZCLCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd) GetType() ZigBeeMsg_ZCLCmd_ZCLCmdType {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_ZCLCmd_ON_OFF
}

func (m *ZigBeeMsg_ZCLCmd) GetOnoffCmd() *ZigBeeMsg_ZCLCmd_OnOffCmd {
	if m != nil {
		return m.OnoffCmd
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd) GetLevelCmd() *ZigBeeMsg_ZCLCmd_LevelCmd {
	if m != nil {
		return m.LevelCmd
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd) GetColorcontrolCmd() *ZigBeeMsg_ZCLCmd_ColorControlCmd {
	if m != nil {
		return m.ColorcontrolCmd
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd) GetIdentifyCmd() *ZigBeeMsg_ZCLCmd_IdentifyCmd {
	if m != nil {
		return m.IdentifyCmd
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd) GetEndpointIndex() uint32 {
	if m != nil {
		return m.EndpointIndex
	}
	return 0
}

// OnOff command definition
type ZigBeeMsg_ZCLCmd_OnOffCmd struct {
	// ZCL OnOff command type
	Type                 ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_OnOffCmd) Reset()         { *m = ZigBeeMsg_ZCLCmd_OnOffCmd{} }
func (m *ZigBeeMsg_ZCLCmd_OnOffCmd) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_ZCLCmd_OnOffCmd) ProtoMessage()    {}
func (*ZigBeeMsg_ZCLCmd_OnOffCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 0}
}

func (m *ZigBeeMsg_ZCLCmd_OnOffCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_OnOffCmd.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_OnOffCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_OnOffCmd.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_OnOffCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_OnOffCmd.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_OnOffCmd) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_OnOffCmd.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_OnOffCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_OnOffCmd.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_OnOffCmd proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_OnOffCmd) GetType() ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_ZCLCmd_OnOffCmd_ON
}

// Level command definition
type ZigBeeMsg_ZCLCmd_LevelCmd struct {
	Type ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType" json:"type,omitempty"`
	// MoveToLevel command
	MoveToLevelParams *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams `protobuf:"bytes,2,opt,name=move_to_level_params,json=moveToLevelParams,proto3" json:"move_to_level_params,omitempty"`
	// Move command
	MoveParams           *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams `protobuf:"bytes,3,opt,name=move_params,json=moveParams,proto3" json:"move_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd) Reset()         { *m = ZigBeeMsg_ZCLCmd_LevelCmd{} }
func (m *ZigBeeMsg_ZCLCmd_LevelCmd) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_ZCLCmd_LevelCmd) ProtoMessage()    {}
func (*ZigBeeMsg_ZCLCmd_LevelCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 1}
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_LevelCmd) GetType() ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_ZCLCmd_LevelCmd_MOVE_TO_LEVEL
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd) GetMoveToLevelParams() *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams {
	if m != nil {
		return m.MoveToLevelParams
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd) GetMoveParams() *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams {
	if m != nil {
		return m.MoveParams
	}
	return nil
}

// MoveToLevel command parameters
type ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams struct {
	// level param <uint8>: The meaning of ‘level’ is device dependent – e.g. for a light it may mean brightness level.
	Level uint32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	// Transition time <uint16>
	TransitionTime       uint32   `protobuf:"varint,2,opt,name=transition_time,json=transitionTime,proto3" json:"transition_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) Reset() {
	*m = ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams{}
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) ProtoMessage() {}
func (*ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 1, 0}
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams) GetTransitionTime() uint32 {
	if m != nil {
		return m.TransitionTime
	}
	return 0
}

// Move command parameters
type ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams struct {
	// |Fade Mode Value | Description  |
	// |      0x00      |     Up       |
	// |      0x01      |    Down      |
	Mode uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// Rate <uint8>: specifies the rate of movement in units per second.
	Rate                 uint32   `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) Reset() {
	*m = ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams{}
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) ProtoMessage()    {}
func (*ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 1, 1}
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams) GetRate() uint32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

// Color Control command definition
type ZigBeeMsg_ZCLCmd_ColorControlCmd struct {
	// ZCLColorControl command type
	Type ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType" json:"type,omitempty"`
	// MoveToHue command params
	MovetohueParams *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams `protobuf:"bytes,2,opt,name=movetohue_params,json=movetohueParams,proto3" json:"movetohue_params,omitempty"`
	// MoveToSat commands params
	MovetosatParams *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams `protobuf:"bytes,3,opt,name=movetosat_params,json=movetosatParams,proto3" json:"movetosat_params,omitempty"`
	// MoveToHueAndSat commands params
	MovetohueandsatParams *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams `protobuf:"bytes,4,opt,name=movetohueandsat_params,json=movetohueandsatParams,proto3" json:"movetohueandsat_params,omitempty"`
	// MoveToColorTemp commands params
	MovetocolortempParams *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams `protobuf:"bytes,5,opt,name=movetocolortemp_params,json=movetocolortempParams,proto3" json:"movetocolortemp_params,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                                                   `json:"-"`
	XXX_unrecognized      []byte                                                     `json:"-"`
	XXX_sizecache         int32                                                      `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) Reset()         { *m = ZigBeeMsg_ZCLCmd_ColorControlCmd{} }
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd) ProtoMessage()    {}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 2}
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) GetType() ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_ZCLCmd_ColorControlCmd_MOVETOHUE
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) GetMovetohueParams() *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams {
	if m != nil {
		return m.MovetohueParams
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) GetMovetosatParams() *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams {
	if m != nil {
		return m.MovetosatParams
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) GetMovetohueandsatParams() *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams {
	if m != nil {
		return m.MovetohueandsatParams
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd) GetMovetocolortempParams() *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams {
	if m != nil {
		return m.MovetocolortempParams
	}
	return nil
}

// MoveToHue command
type ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams struct {
	// Hue <uint8>: specifies the hue to be moved to.
	Hue uint32 `protobuf:"varint,1,opt,name=hue,proto3" json:"hue,omitempty"`
	// Direciton param
	Direction ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam `protobuf:"varint,2,opt,name=direction,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam" json:"direction,omitempty"`
	// Transition time <uint16> : specifies, in 1/10ths of a second, the time that shall be taken to move to the new hue
	TransitionTime       uint32   `protobuf:"varint,3,opt,name=transition_time,json=transitionTime,proto3" json:"transition_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) Reset() {
	*m = ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams{}
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) ProtoMessage() {}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 2, 0}
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) GetHue() uint32 {
	if m != nil {
		return m.Hue
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) GetDirection() ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam {
	if m != nil {
		return m.Direction
	}
	return ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_SHORTEST_DISTANCE
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams) GetTransitionTime() uint32 {
	if m != nil {
		return m.TransitionTime
	}
	return 0
}

type ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams struct {
	// Saturation <uint8>
	Saturation uint32 `protobuf:"varint,1,opt,name=saturation,proto3" json:"saturation,omitempty"`
	// Transition Time <uint16>
	TransitionTime       uint32   `protobuf:"varint,2,opt,name=transition_time,json=transitionTime,proto3" json:"transition_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) Reset() {
	*m = ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams{}
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) ProtoMessage() {}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 2, 1}
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) GetSaturation() uint32 {
	if m != nil {
		return m.Saturation
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams) GetTransitionTime() uint32 {
	if m != nil {
		return m.TransitionTime
	}
	return 0
}

type ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams struct {
	// Hue <uint8>
	Hue uint32 `protobuf:"varint,1,opt,name=hue,proto3" json:"hue,omitempty"`
	// Saturation <uint8>
	Saturation uint32 `protobuf:"varint,2,opt,name=saturation,proto3" json:"saturation,omitempty"`
	// Transition Time <uint16>
	TransitionTime       uint32   `protobuf:"varint,3,opt,name=transition_time,json=transitionTime,proto3" json:"transition_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) Reset() {
	*m = ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams{}
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) ProtoMessage() {}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 2, 2}
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) GetHue() uint32 {
	if m != nil {
		return m.Hue
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) GetSaturation() uint32 {
	if m != nil {
		return m.Saturation
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams) GetTransitionTime() uint32 {
	if m != nil {
		return m.TransitionTime
	}
	return 0
}

type ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams struct {
	// Color Temperature <uint16>
	ColorTemperature uint32 `protobuf:"varint,1,opt,name=color_temperature,json=colorTemperature,proto3" json:"color_temperature,omitempty"`
	// Transition Time <uint16>
	TransitionTime       uint32   `protobuf:"varint,2,opt,name=transition_time,json=transitionTime,proto3" json:"transition_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) Reset() {
	*m = ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams{}
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) ProtoMessage() {}
func (*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 2, 3}
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) GetColorTemperature() uint32 {
	if m != nil {
		return m.ColorTemperature
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams) GetTransitionTime() uint32 {
	if m != nil {
		return m.TransitionTime
	}
	return 0
}

// ZCL Identify command type
type ZigBeeMsg_ZCLCmd_IdentifyCmd struct {
	Type                 ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType    `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType" json:"type,omitempty"`
	IdentifyOnParams     *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams  `protobuf:"bytes,2,opt,name=identify_on_params,json=identifyOnParams,proto3" json:"identify_on_params,omitempty"`
	IdentifyOffParams    *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams `protobuf:"bytes,3,opt,name=identify_off_params,json=identifyOffParams,proto3" json:"identify_off_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) Reset()         { *m = ZigBeeMsg_ZCLCmd_IdentifyCmd{} }
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_ZCLCmd_IdentifyCmd) ProtoMessage()    {}
func (*ZigBeeMsg_ZCLCmd_IdentifyCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 3}
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) GetType() ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_ZCLCmd_IdentifyCmd_IDENTIFY_ON
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) GetIdentifyOnParams() *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams {
	if m != nil {
		return m.IdentifyOnParams
	}
	return nil
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd) GetIdentifyOffParams() *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams {
	if m != nil {
		return m.IdentifyOffParams
	}
	return nil
}

type ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams struct {
	// Transition Time <uint8>
	Endpoint uint32 `protobuf:"varint,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Transition Time in seconds <uint16>
	IdentifyTime         uint32   `protobuf:"varint,2,opt,name=identify_time,json=identifyTime,proto3" json:"identify_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) Reset() {
	*m = ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams{}
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) ProtoMessage() {}
func (*ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 3, 0}
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) GetEndpoint() uint32 {
	if m != nil {
		return m.Endpoint
	}
	return 0
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams) GetIdentifyTime() uint32 {
	if m != nil {
		return m.IdentifyTime
	}
	return 0
}

type ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams struct {
	// Transition Time in seconds <uint16>
	IdentifyTime         uint32   `protobuf:"varint,1,opt,name=identify_time,json=identifyTime,proto3" json:"identify_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) Reset() {
	*m = ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams{}
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) ProtoMessage() {}
func (*ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 0, 3, 1}
}

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams.Merge(m, src)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams.Size(m)
}
func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams proto.InternalMessageInfo

func (m *ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams) GetIdentifyTime() uint32 {
	if m != nil {
		return m.IdentifyTime
	}
	return 0
}

// Network management command definition
type ZigBeeMsg_NetworkMgmtCmd struct {
	// NetworkMgmt command type
	Type ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes" json:"type,omitempty"`
	// PermitJoin params
	PermitJoinParams *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams `protobuf:"bytes,2,opt,name=permit_join_params,json=permitJoinParams,proto3" json:"permit_join_params,omitempty"`
	// Is Proxy Active params
	IsProxyActive bool `protobuf:"varint,3,opt,name=is_proxy_active,json=isProxyActive,proto3" json:"is_proxy_active,omitempty"`
	// Node Leave Network params
	NodeLeaveParams *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams `protobuf:"bytes,4,opt,name=node_leave_params,json=nodeLeaveParams,proto3" json:"node_leave_params,omitempty"`
	// Node Info
	NodeInfo *ZigBeeMsg_NetworkMgmtCmd_NodeDescription `protobuf:"bytes,5,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	// Discovery Nodes info
	ConnectedNodes []*ZigBeeMsg_NetworkMgmtCmd_NodeDescription `protobuf:"bytes,6,rep,name=connected_nodes,json=connectedNodes,proto3" json:"connected_nodes,omitempty"`
	// Network status
	NetworkStatus        *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus `protobuf:"bytes,7,opt,name=network_status,json=networkStatus,proto3" json:"network_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *ZigBeeMsg_NetworkMgmtCmd) Reset()         { *m = ZigBeeMsg_NetworkMgmtCmd{} }
func (m *ZigBeeMsg_NetworkMgmtCmd) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_NetworkMgmtCmd) ProtoMessage()    {}
func (*ZigBeeMsg_NetworkMgmtCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1}
}

func (m *ZigBeeMsg_NetworkMgmtCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd.Unmarshal(m, b)
}
func (m *ZigBeeMsg_NetworkMgmtCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_NetworkMgmtCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd.Merge(m, src)
}
func (m *ZigBeeMsg_NetworkMgmtCmd) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd.Size(m)
}
func (m *ZigBeeMsg_NetworkMgmtCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd proto.InternalMessageInfo

func (m *ZigBeeMsg_NetworkMgmtCmd) GetType() ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_NetworkMgmtCmd_CREATE_NWK
}

func (m *ZigBeeMsg_NetworkMgmtCmd) GetPermitJoinParams() *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams {
	if m != nil {
		return m.PermitJoinParams
	}
	return nil
}

func (m *ZigBeeMsg_NetworkMgmtCmd) GetIsProxyActive() bool {
	if m != nil {
		return m.IsProxyActive
	}
	return false
}

func (m *ZigBeeMsg_NetworkMgmtCmd) GetNodeLeaveParams() *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams {
	if m != nil {
		return m.NodeLeaveParams
	}
	return nil
}

func (m *ZigBeeMsg_NetworkMgmtCmd) GetNodeInfo() *ZigBeeMsg_NetworkMgmtCmd_NodeDescription {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *ZigBeeMsg_NetworkMgmtCmd) GetConnectedNodes() []*ZigBeeMsg_NetworkMgmtCmd_NodeDescription {
	if m != nil {
		return m.ConnectedNodes
	}
	return nil
}

func (m *ZigBeeMsg_NetworkMgmtCmd) GetNetworkStatus() *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus {
	if m != nil {
		return m.NetworkStatus
	}
	return nil
}

// PermitJoin Params Definition
type ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams struct {
	// Joining time : Number of seconds during which devices will be allowed to join the network
	Time                 uint32   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) Reset() {
	*m = ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams{}
}
func (m *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) ProtoMessage()    {}
func (*ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 0}
}

func (m *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams.Merge(m, src)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams.Size(m)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams proto.InternalMessageInfo

func (m *ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

// Node Leave Network Params Definition
type ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams struct {
	// Node Id of the Node you want to leave the network
	NodeId               uint32   `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) Reset() {
	*m = ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams{}
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) ProtoMessage() {}
func (*ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 1}
}

func (m *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams.Unmarshal(m, b)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams.Merge(m, src)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams.Size(m)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams proto.InternalMessageInfo

func (m *ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

// CLuster Description Definition
type ZigBeeMsg_NetworkMgmtCmd_ClusterDescription struct {
	// Cluster server/client type: server (IN) or client (OUT) implementation
	Type ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType" json:"type,omitempty"`
	// Cluster ID : ex 0x0006 (On/off),  0x0008 (Level Control), 0x0201 (Thermostat)
	ClusterId            uint32   `protobuf:"varint,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) Reset() {
	*m = ZigBeeMsg_NetworkMgmtCmd_ClusterDescription{}
}
func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) ProtoMessage() {}
func (*ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 2}
}

func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_ClusterDescription.Unmarshal(m, b)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_ClusterDescription.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_ClusterDescription.Merge(m, src)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_ClusterDescription.Size(m)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_ClusterDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_ClusterDescription proto.InternalMessageInfo

func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) GetType() ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_SERVER_IN
}

func (m *ZigBeeMsg_NetworkMgmtCmd_ClusterDescription) GetClusterId() uint32 {
	if m != nil {
		return m.ClusterId
	}
	return 0
}

// EndPoint Description Definition
type ZigBeeMsg_NetworkMgmtCmd_EndPointDescription struct {
	// EndPoint Profile Index
	EndpointIndex uint32 `protobuf:"varint,1,opt,name=endpoint_index,json=endpointIndex,proto3" json:"endpoint_index,omitempty"`
	// EndPoint Profile ID
	ProfileId uint32 `protobuf:"varint,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	// EndPoint Device ID
	DeviceId uint32 `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// EndPoint Clusters
	Clusters             []*ZigBeeMsg_NetworkMgmtCmd_ClusterDescription `protobuf:"bytes,4,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                       `json:"-"`
	XXX_unrecognized     []byte                                         `json:"-"`
	XXX_sizecache        int32                                          `json:"-"`
}

func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) Reset() {
	*m = ZigBeeMsg_NetworkMgmtCmd_EndPointDescription{}
}
func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) String() string {
	return proto.CompactTextString(m)
}
func (*ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) ProtoMessage() {}
func (*ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 3}
}

func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_EndPointDescription.Unmarshal(m, b)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_EndPointDescription.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_EndPointDescription.Merge(m, src)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_EndPointDescription.Size(m)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_EndPointDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_EndPointDescription proto.InternalMessageInfo

func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) GetEndpointIndex() uint32 {
	if m != nil {
		return m.EndpointIndex
	}
	return 0
}

func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) GetProfileId() uint32 {
	if m != nil {
		return m.ProfileId
	}
	return 0
}

func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) GetDeviceId() uint32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *ZigBeeMsg_NetworkMgmtCmd_EndPointDescription) GetClusters() []*ZigBeeMsg_NetworkMgmtCmd_ClusterDescription {
	if m != nil {
		return m.Clusters
	}
	return nil
}

// Node Info Definition
type ZigBeeMsg_NetworkMgmtCmd_NodeDescription struct {
	// NodeId of the Node
	NodeId uint32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// EUI64 of the Node
	Eui64 uint64 `protobuf:"varint,2,opt,name=eui64,proto3" json:"eui64,omitempty"`
	// EndPoints in the Node
	Endpoints            []*ZigBeeMsg_NetworkMgmtCmd_EndPointDescription `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) Reset() {
	*m = ZigBeeMsg_NetworkMgmtCmd_NodeDescription{}
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_NetworkMgmtCmd_NodeDescription) ProtoMessage()    {}
func (*ZigBeeMsg_NetworkMgmtCmd_NodeDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 4}
}

func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeDescription.Unmarshal(m, b)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeDescription.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeDescription.Merge(m, src)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeDescription.Size(m)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NodeDescription proto.InternalMessageInfo

func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) GetNodeId() uint32 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) GetEui64() uint64 {
	if m != nil {
		return m.Eui64
	}
	return 0
}

func (m *ZigBeeMsg_NetworkMgmtCmd_NodeDescription) GetEndpoints() []*ZigBeeMsg_NetworkMgmtCmd_EndPointDescription {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// Network Status Definition
type ZigBeeMsg_NetworkMgmtCmd_NetworkStatus struct {
	// Status
	Type                 ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status `protobuf:"varint,1,opt,name=type,proto3,enum=matrix_io.malos.v1.comm.ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) Reset() {
	*m = ZigBeeMsg_NetworkMgmtCmd_NetworkStatus{}
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) String() string { return proto.CompactTextString(m) }
func (*ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) ProtoMessage()    {}
func (*ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{0, 1, 5}
}

func (m *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NetworkStatus.Unmarshal(m, b)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NetworkStatus.Marshal(b, m, deterministic)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NetworkStatus.Merge(m, src)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) XXX_Size() int {
	return xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NetworkStatus.Size(m)
}
func (m *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NetworkStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ZigBeeMsg_NetworkMgmtCmd_NetworkStatus proto.InternalMessageInfo

func (m *ZigBeeMsg_NetworkMgmtCmd_NetworkStatus) GetType() ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status {
	if m != nil {
		return m.Type
	}
	return ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_NO_NETWORK
}

// ZWaveMsg params to send commands through the Z/IP Gateway
type ZWaveMsg struct {
	// Malos operation {SEND,ADDNODE,REMOVENODE,LIST,...}
	Operation ZWaveMsg_ZWaveOperations `protobuf:"varint,1,opt,name=operation,proto3,enum=matrix_io.malos.v1.comm.ZWaveMsg_ZWaveOperations" json:"operation,omitempty"`
	// service name of the device to send ZWave commands
	ServiceToSend string `protobuf:"bytes,2,opt,name=service_to_send,json=serviceToSend,proto3" json:"service_to_send,omitempty"`
	// ZWave command, when operation=SEND
	ZwaveCmd *ZWaveMsg_ZWaveCommand `protobuf:"bytes,3,opt,name=zwave_cmd,json=zwaveCmd,proto3" json:"zwave_cmd,omitempty"`
	// List of ZWave devices/nodes, when operation=LIST
	Node []*ZWaveMsg_ZWaveNode `protobuf:"bytes,4,rep,name=node,proto3" json:"node,omitempty"`
	// Result of Malos Operation
	Result               bool     `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZWaveMsg) Reset()         { *m = ZWaveMsg{} }
func (m *ZWaveMsg) String() string { return proto.CompactTextString(m) }
func (*ZWaveMsg) ProtoMessage()    {}
func (*ZWaveMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{1}
}

func (m *ZWaveMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZWaveMsg.Unmarshal(m, b)
}
func (m *ZWaveMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZWaveMsg.Marshal(b, m, deterministic)
}
func (m *ZWaveMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZWaveMsg.Merge(m, src)
}
func (m *ZWaveMsg) XXX_Size() int {
	return xxx_messageInfo_ZWaveMsg.Size(m)
}
func (m *ZWaveMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ZWaveMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ZWaveMsg proto.InternalMessageInfo

func (m *ZWaveMsg) GetOperation() ZWaveMsg_ZWaveOperations {
	if m != nil {
		return m.Operation
	}
	return ZWaveMsg_UNDEF
}

func (m *ZWaveMsg) GetServiceToSend() string {
	if m != nil {
		return m.ServiceToSend
	}
	return ""
}

func (m *ZWaveMsg) GetZwaveCmd() *ZWaveMsg_ZWaveCommand {
	if m != nil {
		return m.ZwaveCmd
	}
	return nil
}

func (m *ZWaveMsg) GetNode() []*ZWaveMsg_ZWaveNode {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ZWaveMsg) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// ZWave command with params
type ZWaveMsg_ZWaveCommandInfo struct {
	Cmd                  ZWaveCmdType `protobuf:"varint,1,opt,name=cmd,proto3,enum=matrix_io.malos.v1.comm.ZWaveCmdType" json:"cmd,omitempty"`
	Param                []string     `protobuf:"bytes,2,rep,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ZWaveMsg_ZWaveCommandInfo) Reset()         { *m = ZWaveMsg_ZWaveCommandInfo{} }
func (m *ZWaveMsg_ZWaveCommandInfo) String() string { return proto.CompactTextString(m) }
func (*ZWaveMsg_ZWaveCommandInfo) ProtoMessage()    {}
func (*ZWaveMsg_ZWaveCommandInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{1, 0}
}

func (m *ZWaveMsg_ZWaveCommandInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZWaveMsg_ZWaveCommandInfo.Unmarshal(m, b)
}
func (m *ZWaveMsg_ZWaveCommandInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZWaveMsg_ZWaveCommandInfo.Marshal(b, m, deterministic)
}
func (m *ZWaveMsg_ZWaveCommandInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZWaveMsg_ZWaveCommandInfo.Merge(m, src)
}
func (m *ZWaveMsg_ZWaveCommandInfo) XXX_Size() int {
	return xxx_messageInfo_ZWaveMsg_ZWaveCommandInfo.Size(m)
}
func (m *ZWaveMsg_ZWaveCommandInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ZWaveMsg_ZWaveCommandInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ZWaveMsg_ZWaveCommandInfo proto.InternalMessageInfo

func (m *ZWaveMsg_ZWaveCommandInfo) GetCmd() ZWaveCmdType {
	if m != nil {
		return m.Cmd
	}
	return ZWaveCmdType_CMD_UNDEFINED
}

func (m *ZWaveMsg_ZWaveCommandInfo) GetParam() []string {
	if m != nil {
		return m.Param
	}
	return nil
}

// ZWave class with params
type ZWaveMsg_ZWaveClassInfo struct {
	ZwaveClass           ZWaveClassType               `protobuf:"varint,1,opt,name=zwave_class,json=zwaveClass,proto3,enum=matrix_io.malos.v1.comm.ZWaveClassType" json:"zwave_class,omitempty"`
	Command              []*ZWaveMsg_ZWaveCommandInfo `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ZWaveMsg_ZWaveClassInfo) Reset()         { *m = ZWaveMsg_ZWaveClassInfo{} }
func (m *ZWaveMsg_ZWaveClassInfo) String() string { return proto.CompactTextString(m) }
func (*ZWaveMsg_ZWaveClassInfo) ProtoMessage()    {}
func (*ZWaveMsg_ZWaveClassInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{1, 1}
}

func (m *ZWaveMsg_ZWaveClassInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZWaveMsg_ZWaveClassInfo.Unmarshal(m, b)
}
func (m *ZWaveMsg_ZWaveClassInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZWaveMsg_ZWaveClassInfo.Marshal(b, m, deterministic)
}
func (m *ZWaveMsg_ZWaveClassInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZWaveMsg_ZWaveClassInfo.Merge(m, src)
}
func (m *ZWaveMsg_ZWaveClassInfo) XXX_Size() int {
	return xxx_messageInfo_ZWaveMsg_ZWaveClassInfo.Size(m)
}
func (m *ZWaveMsg_ZWaveClassInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ZWaveMsg_ZWaveClassInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ZWaveMsg_ZWaveClassInfo proto.InternalMessageInfo

func (m *ZWaveMsg_ZWaveClassInfo) GetZwaveClass() ZWaveClassType {
	if m != nil {
		return m.ZwaveClass
	}
	return ZWaveClassType_COMMAND_CLASS_NO_OPERATION
}

func (m *ZWaveMsg_ZWaveClassInfo) GetCommand() []*ZWaveMsg_ZWaveCommandInfo {
	if m != nil {
		return m.Command
	}
	return nil
}

// ZWave devices or nodes
type ZWaveMsg_ZWaveNode struct {
	// unique service name (device address)
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// list of ZWave classes supported by the device
	ZwaveClass           []*ZWaveMsg_ZWaveClassInfo `protobuf:"bytes,2,rep,name=zwave_class,json=zwaveClass,proto3" json:"zwave_class,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ZWaveMsg_ZWaveNode) Reset()         { *m = ZWaveMsg_ZWaveNode{} }
func (m *ZWaveMsg_ZWaveNode) String() string { return proto.CompactTextString(m) }
func (*ZWaveMsg_ZWaveNode) ProtoMessage()    {}
func (*ZWaveMsg_ZWaveNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{1, 2}
}

func (m *ZWaveMsg_ZWaveNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZWaveMsg_ZWaveNode.Unmarshal(m, b)
}
func (m *ZWaveMsg_ZWaveNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZWaveMsg_ZWaveNode.Marshal(b, m, deterministic)
}
func (m *ZWaveMsg_ZWaveNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZWaveMsg_ZWaveNode.Merge(m, src)
}
func (m *ZWaveMsg_ZWaveNode) XXX_Size() int {
	return xxx_messageInfo_ZWaveMsg_ZWaveNode.Size(m)
}
func (m *ZWaveMsg_ZWaveNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ZWaveMsg_ZWaveNode.DiscardUnknown(m)
}

var xxx_messageInfo_ZWaveMsg_ZWaveNode proto.InternalMessageInfo

func (m *ZWaveMsg_ZWaveNode) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ZWaveMsg_ZWaveNode) GetZwaveClass() []*ZWaveMsg_ZWaveClassInfo {
	if m != nil {
		return m.ZwaveClass
	}
	return nil
}

// ZWave command to sent
type ZWaveMsg_ZWaveCommand struct {
	Zwclass              ZWaveClassType `protobuf:"varint,1,opt,name=zwclass,proto3,enum=matrix_io.malos.v1.comm.ZWaveClassType" json:"zwclass,omitempty"`
	Cmd                  ZWaveCmdType   `protobuf:"varint,2,opt,name=cmd,proto3,enum=matrix_io.malos.v1.comm.ZWaveCmdType" json:"cmd,omitempty"`
	Params               []byte         `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ZWaveMsg_ZWaveCommand) Reset()         { *m = ZWaveMsg_ZWaveCommand{} }
func (m *ZWaveMsg_ZWaveCommand) String() string { return proto.CompactTextString(m) }
func (*ZWaveMsg_ZWaveCommand) ProtoMessage()    {}
func (*ZWaveMsg_ZWaveCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{1, 3}
}

func (m *ZWaveMsg_ZWaveCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZWaveMsg_ZWaveCommand.Unmarshal(m, b)
}
func (m *ZWaveMsg_ZWaveCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZWaveMsg_ZWaveCommand.Marshal(b, m, deterministic)
}
func (m *ZWaveMsg_ZWaveCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZWaveMsg_ZWaveCommand.Merge(m, src)
}
func (m *ZWaveMsg_ZWaveCommand) XXX_Size() int {
	return xxx_messageInfo_ZWaveMsg_ZWaveCommand.Size(m)
}
func (m *ZWaveMsg_ZWaveCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ZWaveMsg_ZWaveCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ZWaveMsg_ZWaveCommand proto.InternalMessageInfo

func (m *ZWaveMsg_ZWaveCommand) GetZwclass() ZWaveClassType {
	if m != nil {
		return m.Zwclass
	}
	return ZWaveClassType_COMMAND_CLASS_NO_OPERATION
}

func (m *ZWaveMsg_ZWaveCommand) GetCmd() ZWaveCmdType {
	if m != nil {
		return m.Cmd
	}
	return ZWaveCmdType_CMD_UNDEFINED
}

func (m *ZWaveMsg_ZWaveCommand) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

// LIRC service params
type LircParams struct {
	// IR remote device name
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// IR command
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// For transport of LIRC remote devices configuration.
	// Format: http://www.lirc.org/html/configuration-guide.html
	// Admobilize config remotes resources:
	// http://assets.admobilize.com/lirc-remotes/
	Config               string   `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LircParams) Reset()         { *m = LircParams{} }
func (m *LircParams) String() string { return proto.CompactTextString(m) }
func (*LircParams) ProtoMessage()    {}
func (*LircParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf8e488e55b67472, []int{2}
}

func (m *LircParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LircParams.Unmarshal(m, b)
}
func (m *LircParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LircParams.Marshal(b, m, deterministic)
}
func (m *LircParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LircParams.Merge(m, src)
}
func (m *LircParams) XXX_Size() int {
	return xxx_messageInfo_LircParams.Size(m)
}
func (m *LircParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LircParams.DiscardUnknown(m)
}

var xxx_messageInfo_LircParams proto.InternalMessageInfo

func (m *LircParams) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *LircParams) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *LircParams) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func init() {
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_ZigBeeCmdType", ZigBeeMsg_ZigBeeCmdType_name, ZigBeeMsg_ZigBeeCmdType_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_ZCLCmdType", ZigBeeMsg_ZCLCmd_ZCLCmdType_name, ZigBeeMsg_ZCLCmd_ZCLCmdType_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType", ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType_name, ZigBeeMsg_ZCLCmd_OnOffCmd_ZCLOnOffCmdType_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType", ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType_name, ZigBeeMsg_ZCLCmd_LevelCmd_ZCLLevelCmdType_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType", ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType_name, ZigBeeMsg_ZCLCmd_ColorControlCmd_ZCLColorControlCmdType_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam", ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam_name, ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams_DirectionParam_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType", ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType_name, ZigBeeMsg_ZCLCmd_IdentifyCmd_ZCLIdentifyCmdType_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes", ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes_name, ZigBeeMsg_NetworkMgmtCmd_NetworkMgmtCmdTypes_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType", ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType_name, ZigBeeMsg_NetworkMgmtCmd_ClusterDescription_ClusterInOutType_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status", ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status_name, ZigBeeMsg_NetworkMgmtCmd_NetworkStatus_Status_value)
	proto.RegisterEnum("matrix_io.malos.v1.comm.ZWaveMsg_ZWaveOperations", ZWaveMsg_ZWaveOperations_name, ZWaveMsg_ZWaveOperations_value)
	proto.RegisterType((*ZigBeeMsg)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_OnOffCmd)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.OnOffCmd")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_LevelCmd)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.LevelCmd")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_LevelCmd_MoveToLevelCmdParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.LevelCmd.MoveToLevelCmdParams")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_LevelCmd_MoveCmdParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.LevelCmd.MoveCmdParams")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_ColorControlCmd)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.ColorControlCmd")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueCmdParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueCmdParams")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToSatCmdParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToSatCmdParams")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToHueAndSatCmdParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToHueAndSatCmdParams")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_ColorControlCmd_MoveToColorTempCmdParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.ColorControlCmd.MoveToColorTempCmdParams")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_IdentifyCmd)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.IdentifyCmd")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOnCmdParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.IdentifyCmd.IdentifyOnCmdParams")
	proto.RegisterType((*ZigBeeMsg_ZCLCmd_IdentifyCmd_IdentifyOffCmdParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.ZCLCmd.IdentifyCmd.IdentifyOffCmdParams")
	proto.RegisterType((*ZigBeeMsg_NetworkMgmtCmd)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.NetworkMgmtCmd")
	proto.RegisterType((*ZigBeeMsg_NetworkMgmtCmd_PermitJoinParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.NetworkMgmtCmd.PermitJoinParams")
	proto.RegisterType((*ZigBeeMsg_NetworkMgmtCmd_NodeLeaveNetParams)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.NetworkMgmtCmd.NodeLeaveNetParams")
	proto.RegisterType((*ZigBeeMsg_NetworkMgmtCmd_ClusterDescription)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.NetworkMgmtCmd.ClusterDescription")
	proto.RegisterType((*ZigBeeMsg_NetworkMgmtCmd_EndPointDescription)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.NetworkMgmtCmd.EndPointDescription")
	proto.RegisterType((*ZigBeeMsg_NetworkMgmtCmd_NodeDescription)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.NetworkMgmtCmd.NodeDescription")
	proto.RegisterType((*ZigBeeMsg_NetworkMgmtCmd_NetworkStatus)(nil), "matrix_io.malos.v1.comm.ZigBeeMsg.NetworkMgmtCmd.NetworkStatus")
	proto.RegisterType((*ZWaveMsg)(nil), "matrix_io.malos.v1.comm.ZWaveMsg")
	proto.RegisterType((*ZWaveMsg_ZWaveCommandInfo)(nil), "matrix_io.malos.v1.comm.ZWaveMsg.ZWaveCommandInfo")
	proto.RegisterType((*ZWaveMsg_ZWaveClassInfo)(nil), "matrix_io.malos.v1.comm.ZWaveMsg.ZWaveClassInfo")
	proto.RegisterType((*ZWaveMsg_ZWaveNode)(nil), "matrix_io.malos.v1.comm.ZWaveMsg.ZWaveNode")
	proto.RegisterType((*ZWaveMsg_ZWaveCommand)(nil), "matrix_io.malos.v1.comm.ZWaveMsg.ZWaveCommand")
	proto.RegisterType((*LircParams)(nil), "matrix_io.malos.v1.comm.LircParams")
}

func init() { proto.RegisterFile("matrix_io/malos/v1/comm.proto", fileDescriptor_cf8e488e55b67472) }

var fileDescriptor_cf8e488e55b67472 = []byte{
	// 2083 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x59, 0x4f, 0x93, 0xdb, 0x48,
	0x15, 0x8f, 0xec, 0x19, 0xff, 0x79, 0x33, 0xb6, 0x95, 0x4e, 0x76, 0xd6, 0xa5, 0x65, 0xa9, 0x60,
	0x6a, 0x37, 0x81, 0xad, 0x78, 0x36, 0x61, 0x21, 0x50, 0x1c, 0x16, 0x8f, 0xad, 0x99, 0x51, 0x62,
	0x4b, 0x46, 0xd6, 0x38, 0x9b, 0x2c, 0x8b, 0x56, 0x6b, 0xc9, 0x13, 0x2d, 0x96, 0xe4, 0xb2, 0xe4,
	0x49, 0x32, 0x55, 0x1c, 0x38, 0x72, 0xe5, 0xca, 0x8d, 0x2a, 0x0a, 0x8a, 0x03, 0x5f, 0x81, 0x33,
	0x17, 0xaa, 0xb8, 0xc2, 0x89, 0x23, 0x9f, 0x02, 0xea, 0x75, 0xb7, 0x64, 0xc9, 0x76, 0xb2, 0x1e,
	0x27, 0xa7, 0xe9, 0xf7, 0xda, 0xfd, 0x7b, 0xaf, 0xdf, 0xff, 0xd6, 0xc0, 0xfb, 0x9e, 0x15, 0xcd,
	0xdc, 0x17, 0xa6, 0x1b, 0x1c, 0x7a, 0xd6, 0x24, 0x08, 0x0f, 0x2f, 0xee, 0x1d, 0x8e, 0x02, 0xcf,
	0x6b, 0x4e, 0x67, 0x41, 0x14, 0x90, 0x77, 0x93, 0xed, 0x26, 0xdd, 0x6e, 0x5e, 0xdc, 0x6b, 0xe2,
	0xb6, 0x74, 0x7b, 0xcd, 0xb9, 0xcb, 0xe7, 0xd6, 0x85, 0x63, 0xe2, 0xb6, 0xe5, 0xdb, 0x21, 0x43,
	0x68, 0xfc, 0xfb, 0x0e, 0x94, 0x9f, 0xba, 0xe7, 0x47, 0x8e, 0xd3, 0x0b, 0xcf, 0x49, 0x07, 0x76,
	0xa2, 0x97, 0x53, 0xa7, 0x2e, 0xdc, 0x12, 0xee, 0x54, 0xef, 0x7f, 0xdc, 0x7c, 0x05, 0x7c, 0x33,
	0x39, 0xc1, 0x57, 0x6d, 0xcf, 0x36, 0x5e, 0x4e, 0x1d, 0x9d, 0x9e, 0x26, 0x47, 0x50, 0xbc, 0x1c,
	0x4d, 0xcc, 0x91, 0x67, 0xd7, 0x73, 0xb7, 0x84, 0x3b, 0x7b, 0xf7, 0xbf, 0xb7, 0x09, 0x50, 0xbb,
	0xdb, 0xf6, 0x6c, 0xbd, 0x70, 0x39, 0x9a, 0xb4, 0x3d, 0x9b, 0x7c, 0x0e, 0xa2, 0xef, 0x44, 0xcf,
	0x83, 0xd9, 0xaf, 0x4c, 0xef, 0xdc, 0x8b, 0x28, 0x58, 0x9e, 0x82, 0xdd, 0xdb, 0x00, 0x4c, 0x65,
	0x47, 0x7b, 0xe7, 0x5e, 0x84, 0xa0, 0x55, 0x3f, 0x43, 0x4b, 0xff, 0xa8, 0x43, 0x81, 0xc9, 0x23,
	0xa7, 0x99, 0x1b, 0x7f, 0xb2, 0xb1, 0xa2, 0xfc, 0x4f, 0xea, 0xd6, 0x1a, 0x94, 0x03, 0x3f, 0x18,
	0x8f, 0x53, 0xf7, 0xbe, 0xbf, 0x39, 0x9c, 0xe6, 0x6b, 0xe3, 0x31, 0xea, 0x5a, 0xa2, 0x20, 0xa8,
	0x9a, 0x06, 0xe5, 0x89, 0x73, 0xe1, 0x4c, 0x52, 0x77, 0xbf, 0x02, 0x60, 0x17, 0x8f, 0x52, 0xc0,
	0x09, 0x5f, 0x11, 0x1b, 0xc4, 0x51, 0x30, 0x09, 0x66, 0xa3, 0xc0, 0x8f, 0x66, 0x01, 0xc3, 0xdd,
	0xa1, 0xb8, 0x3f, 0xd9, 0x1c, 0xb7, 0x8d, 0x08, 0x6d, 0x86, 0x80, 0xf0, 0xb5, 0x34, 0x24, 0x4a,
	0xf9, 0x0c, 0xf6, 0x5d, 0xdb, 0xf1, 0x23, 0x77, 0xfc, 0x92, 0x4a, 0xd8, 0xa5, 0x12, 0x7e, 0xb8,
	0xb9, 0x04, 0x85, 0x9f, 0x46, 0xf4, 0x3d, 0x77, 0x41, 0x90, 0x77, 0xa1, 0xe8, 0x07, 0xb6, 0x63,
	0xba, 0x76, 0xbd, 0x70, 0x4b, 0xb8, 0x53, 0xd1, 0x0b, 0x48, 0x2a, 0x36, 0xf9, 0x00, 0xaa, 0x8e,
	0x6f, 0x4f, 0x03, 0xd7, 0x8f, 0x4c, 0xd7, 0xb7, 0x9d, 0x17, 0xf5, 0x22, 0xdd, 0xaf, 0xc4, 0x5c,
	0x05, 0x99, 0xd2, 0xef, 0x04, 0x28, 0xc5, 0x76, 0x26, 0xc3, 0x8c, 0xe3, 0x8f, 0xae, 0xee, 0x29,
	0xa4, 0xe3, 0xf5, 0x22, 0x0c, 0x1a, 0x4d, 0xa8, 0x2d, 0x6d, 0x90, 0x02, 0xe4, 0x34, 0x55, 0xbc,
	0x46, 0x8a, 0x90, 0xd7, 0x8e, 0x8f, 0x45, 0x81, 0x00, 0x14, 0x0c, 0xed, 0xe4, 0xa4, 0x2b, 0x8b,
	0x39, 0xe9, 0x7f, 0x79, 0x28, 0xc5, 0xbe, 0xda, 0x5e, 0xa9, 0x18, 0x01, 0xe9, 0x78, 0x9d, 0x8a,
	0xcd, 0x17, 0x70, 0xd3, 0x0b, 0x2e, 0x1c, 0x33, 0x0a, 0x4c, 0x16, 0x52, 0x53, 0x6b, 0x66, 0x79,
	0x21, 0x0f, 0xd3, 0x93, 0x2d, 0xe4, 0xf4, 0x82, 0x0b, 0xc7, 0x08, 0x62, 0xb2, 0x4f, 0xe1, 0xf4,
	0xeb, 0xde, 0x82, 0xcb, 0x58, 0xc4, 0x82, 0x3d, 0x2a, 0x99, 0x0b, 0x64, 0x61, 0xfc, 0xb3, 0x2d,
	0x05, 0x2e, 0x24, 0x01, 0x82, 0xb2, 0xb5, 0x74, 0x06, 0x37, 0xd7, 0x69, 0x43, 0x6e, 0xc2, 0x2e,
	0xbd, 0x2c, 0xb5, 0x66, 0x45, 0x67, 0x04, 0xb9, 0x0d, 0xb5, 0x68, 0x66, 0xf9, 0xa1, 0x1b, 0xb9,
	0x81, 0x6f, 0x46, 0xae, 0xe7, 0x50, 0x2b, 0x54, 0xf4, 0xea, 0x82, 0x6d, 0xb8, 0x9e, 0x23, 0x3d,
	0x80, 0x4a, 0x46, 0x26, 0x21, 0xb0, 0xe3, 0x05, 0xb6, 0xc3, 0xe1, 0xe8, 0x1a, 0x79, 0x33, 0x2b,
	0x8a, 0x21, 0xe8, 0x9a, 0x47, 0x40, 0xda, 0x0b, 0xe4, 0x3a, 0x54, 0x7a, 0xda, 0x50, 0x36, 0x0d,
	0xcd, 0xec, 0xca, 0x43, 0xb9, 0x2b, 0x5e, 0x23, 0x25, 0xd8, 0x41, 0x96, 0x28, 0x48, 0x7f, 0x07,
	0xa8, 0x2d, 0x65, 0x15, 0xb1, 0x33, 0x81, 0xd0, 0xdf, 0x3a, 0x3d, 0x29, 0x3b, 0xcb, 0x4a, 0x85,
	0xc5, 0x73, 0x10, 0xd1, 0x8e, 0x51, 0xf0, 0x6c, 0xee, 0x64, 0x43, 0xa2, 0xbb, 0xbd, 0x44, 0xe6,
	0x8b, 0xd3, 0x79, 0xca, 0x5b, 0xb5, 0x44, 0x0a, 0x37, 0x65, 0x22, 0x38, 0xb4, 0xa2, 0x6c, 0x68,
	0xbc, 0xb1, 0xe0, 0x81, 0x15, 0xad, 0x08, 0x0e, 0xad, 0x88, 0x0b, 0xfe, 0xad, 0x00, 0x07, 0x89,
	0x32, 0xd8, 0x06, 0x17, 0xf2, 0x59, 0x25, 0xd4, 0xdf, 0xc2, 0xc5, 0x5b, 0xbe, 0x9d, 0xd1, 0xe2,
	0x9d, 0x25, 0x89, 0x2b, 0xba, 0xd0, 0x12, 0x1a, 0x39, 0xde, 0x34, 0xd6, 0x65, 0xf7, 0xed, 0xe8,
	0x42, 0xb9, 0x86, 0xe3, 0x4d, 0x57, 0x74, 0x49, 0x24, 0xf2, 0x1c, 0xfa, 0x7d, 0x0e, 0xc8, 0xaa,
	0xe3, 0x88, 0x08, 0xf9, 0x67, 0xf3, 0x38, 0xe2, 0x71, 0x49, 0x5e, 0x42, 0xd9, 0x76, 0x67, 0xce,
	0x08, 0xd3, 0x84, 0xc6, 0x4a, 0xf5, 0xfe, 0xe7, 0x6f, 0x33, 0x56, 0x9a, 0x9d, 0x18, 0x9d, 0xd2,
	0xfa, 0x42, 0xda, 0xba, 0xcc, 0xcd, 0xaf, 0xcb, 0xdc, 0x86, 0x06, 0xd5, 0x2c, 0x0a, 0x79, 0x07,
	0xae, 0x0f, 0x4e, 0x35, 0xdd, 0x90, 0x07, 0x86, 0xd9, 0x51, 0x06, 0x46, 0x4b, 0x6d, 0xcb, 0xe2,
	0x35, 0x72, 0x13, 0xc4, 0xae, 0xa6, 0x9e, 0x64, 0xb8, 0x02, 0x96, 0xeb, 0xb3, 0xbe, 0x98, 0xc3,
	0x0c, 0xed, 0x68, 0x8f, 0x55, 0x31, 0x2f, 0x7d, 0x11, 0x1b, 0x27, 0xed, 0x56, 0xf2, 0x6d, 0x80,
	0xd0, 0x8a, 0xe6, 0x33, 0x8b, 0xda, 0x82, 0xd9, 0x28, 0xc5, 0xd9, 0xbc, 0xd2, 0xcc, 0xa1, 0xfe,
	0xaa, 0xd8, 0x59, 0xe3, 0x81, 0xac, 0xd8, 0xdc, 0x26, 0x62, 0xd7, 0x9a, 0x49, 0x9a, 0xc6, 0x62,
	0x57, 0xc3, 0x84, 0x7c, 0x04, 0xd7, 0x69, 0x88, 0x98, 0x18, 0x23, 0xce, 0x0c, 0xd1, 0x63, 0x25,
	0xd8, 0x0c, 0x61, 0x2c, 0xf8, 0x1b, 0x5f, 0xb4, 0xf1, 0x25, 0x1c, 0xac, 0xaf, 0x47, 0xa4, 0x02,
	0x65, 0xac, 0x86, 0x86, 0x76, 0x7a, 0x86, 0x8e, 0x49, 0xc8, 0x41, 0xcb, 0x10, 0x05, 0x72, 0x03,
	0x6a, 0xc9, 0x6e, 0x4b, 0xed, 0x20, 0x33, 0xb7, 0x60, 0xb6, 0xb5, 0x2e, 0xba, 0xb6, 0xd7, 0x17,
	0xf3, 0xd2, 0x5f, 0x77, 0x60, 0x2f, 0x35, 0x3f, 0x90, 0x5f, 0x64, 0xea, 0xe8, 0xe9, 0x56, 0x43,
	0x08, 0xb2, 0x52, 0x64, 0xa6, 0x7e, 0x92, 0x64, 0xd4, 0x09, 0xfc, 0x6c, 0x05, 0x55, 0xb6, 0x93,
	0x15, 0xaf, 0x35, 0x7f, 0x91, 0xb3, 0xa2, 0x9b, 0x30, 0xb9, 0x7b, 0x2e, 0xe1, 0xc6, 0x42, 0xf0,
	0x78, 0x9c, 0x2d, 0xa1, 0x0f, 0xdf, 0x50, 0x32, 0x1d, 0x5c, 0xe2, 0x8e, 0xee, 0x2e, 0xb8, 0xbc,
	0x54, 0x0c, 0xe1, 0xc6, 0x1a, 0x25, 0x89, 0x04, 0xa5, 0x78, 0xda, 0xe2, 0x81, 0x92, 0xd0, 0xe4,
	0xbb, 0x50, 0x49, 0xd4, 0x4d, 0x85, 0x47, 0x32, 0x27, 0xd2, 0x70, 0xfc, 0x29, 0xdc, 0x5c, 0xa7,
	0xc2, 0xea, 0x61, 0x61, 0xf5, 0x70, 0xe3, 0x01, 0x90, 0x55, 0x2f, 0x91, 0x1a, 0xec, 0x29, 0x1d,
	0x59, 0x35, 0x94, 0xe3, 0x27, 0x26, 0x9d, 0xc0, 0x44, 0xd8, 0x5f, 0x30, 0x70, 0x14, 0x6b, 0x74,
	0x00, 0x16, 0x93, 0x3c, 0x0e, 0x66, 0x9a, 0x4a, 0x77, 0xae, 0x91, 0x32, 0xec, 0xb2, 0x5e, 0x2d,
	0x60, 0xfb, 0xa6, 0x41, 0x66, 0xb6, 0x35, 0xd5, 0xd0, 0xb5, 0xae, 0x98, 0x23, 0xfb, 0x50, 0x8a,
	0x91, 0xc4, 0xbc, 0xf4, 0xdf, 0x0a, 0x54, 0xb3, 0x6f, 0x0e, 0xf2, 0x24, 0x13, 0x79, 0xf2, 0x95,
	0x1f, 0x2d, 0x4b, 0x24, 0xaa, 0x17, 0xf2, 0xb0, 0x9b, 0x02, 0x99, 0x3a, 0x33, 0xcf, 0x8d, 0xcc,
	0xaf, 0x03, 0x77, 0x29, 0xec, 0x8e, 0xae, 0x2e, 0xa8, 0x4f, 0xb1, 0x1e, 0x06, 0xae, 0x1f, 0xc7,
	0xdb, 0x74, 0x89, 0x43, 0x3e, 0x84, 0x9a, 0x1b, 0x9a, 0xd3, 0x59, 0xf0, 0xe2, 0xa5, 0x69, 0x8d,
	0x22, 0xf7, 0x82, 0xd5, 0x94, 0x92, 0x5e, 0x71, 0xc3, 0x3e, 0x72, 0x5b, 0x94, 0x49, 0xa6, 0x70,
	0x9d, 0x4e, 0xe8, 0x13, 0xc7, 0x5a, 0xcc, 0x7c, 0xac, 0xb1, 0x76, 0xb6, 0xb0, 0x40, 0x60, 0x3b,
	0x5d, 0x44, 0x52, 0x9d, 0x28, 0x6e, 0xe8, 0x7e, 0xcc, 0xe3, 0x9a, 0xfd, 0x12, 0xca, 0xec, 0x4d,
	0xe0, 0x8f, 0x03, 0xde, 0x36, 0x5b, 0xdb, 0x49, 0xea, 0x38, 0xe1, 0x68, 0xe6, 0x4e, 0xb1, 0x58,
	0xe9, 0x25, 0xfa, 0xb0, 0xf0, 0xc7, 0x01, 0xf9, 0x1a, 0x6a, 0xa3, 0xc0, 0xf7, 0x9d, 0x51, 0xe4,
	0xd8, 0x26, 0x72, 0xc3, 0x7a, 0xe1, 0x56, 0xfe, 0xed, 0x48, 0xa9, 0x26, 0xc8, 0xb8, 0x13, 0x92,
	0x31, 0xc4, 0x0f, 0x55, 0x33, 0x8c, 0xac, 0x68, 0x1e, 0xd2, 0x67, 0xcc, 0xde, 0xfd, 0x4f, 0xb7,
	0x0e, 0x9e, 0x01, 0x85, 0xd1, 0x2b, 0x7e, 0x9a, 0x94, 0x3e, 0x04, 0x71, 0xd9, 0xe7, 0x38, 0xc8,
	0xa6, 0x92, 0x8b, 0xae, 0xa5, 0xbb, 0x40, 0x56, 0x5d, 0x90, 0x7e, 0x85, 0x09, 0xe9, 0x57, 0x98,
	0xf4, 0x4f, 0x01, 0x48, 0x7b, 0x32, 0x0f, 0x23, 0x67, 0x96, 0xba, 0x25, 0x71, 0x33, 0x89, 0x70,
	0x76, 0xf5, 0xbb, 0xac, 0x62, 0xc6, 0x2c, 0xc5, 0xd7, 0xe6, 0x51, 0xaa, 0x1e, 0xbf, 0x0f, 0x30,
	0x62, 0x3b, 0xa8, 0x1d, 0x2b, 0x32, 0x65, 0xce, 0x51, 0xec, 0xc6, 0x3d, 0x10, 0x97, 0x0f, 0x62,
	0xa7, 0x19, 0xc8, 0xfa, 0x50, 0xd6, 0x4d, 0x05, 0x0b, 0x44, 0x15, 0xa0, 0xdd, 0x55, 0x64, 0xd5,
	0x30, 0xb5, 0x33, 0x43, 0x14, 0xa4, 0x7f, 0x09, 0x70, 0x43, 0xf6, 0xed, 0x3e, 0x96, 0xb1, 0xf4,
	0xa5, 0x56, 0x5f, 0x9c, 0xc2, 0x9a, 0x17, 0x27, 0x2a, 0x34, 0x9d, 0x05, 0x63, 0x77, 0xe2, 0xa4,
	0x14, 0xe2, 0x1c, 0xc5, 0x26, 0xef, 0x41, 0xd9, 0x76, 0x2e, 0xdc, 0x11, 0xdd, 0x65, 0x4d, 0xba,
	0xc4, 0x18, 0x8a, 0x4d, 0xbe, 0x84, 0x12, 0x57, 0x1d, 0x53, 0x28, 0xbf, 0x5d, 0x0a, 0xad, 0xda,
	0x4e, 0x4f, 0x50, 0xa5, 0x3f, 0x0a, 0x50, 0x5b, 0x8a, 0xc9, 0x57, 0x7a, 0x17, 0x5f, 0x53, 0xce,
	0xdc, 0xfd, 0xd1, 0x27, 0xf4, 0x16, 0x3b, 0x3a, 0x23, 0xc8, 0x08, 0xca, 0xf1, 0x8d, 0xb1, 0xfd,
	0xa0, 0x96, 0x5b, 0x94, 0xba, 0x35, 0x16, 0xd6, 0x17, 0xb8, 0xd2, 0x7f, 0x04, 0xa8, 0x64, 0x02,
	0x9a, 0x3c, 0xcd, 0xc4, 0xd4, 0xf1, 0x1b, 0xe6, 0x47, 0x93, 0xa7, 0x09, 0x7b, 0xc0, 0x47, 0x50,
	0xe0, 0x52, 0xaa, 0x00, 0xaa, 0x66, 0xaa, 0xb2, 0xf1, 0x58, 0xd3, 0x1f, 0x89, 0xd7, 0x70, 0xe2,
	0x78, 0xa8, 0x29, 0xaa, 0xa2, 0x9e, 0x24, 0x4c, 0x81, 0x10, 0xa8, 0x22, 0x53, 0xee, 0x24, 0xbc,
	0x1c, 0xf9, 0x16, 0xd4, 0xb3, 0x3c, 0x53, 0xd5, 0xcc, 0x7e, 0x4b, 0x97, 0x55, 0x43, 0xcc, 0x23,
	0x4c, 0x57, 0x6e, 0x0d, 0xd3, 0x30, 0x3b, 0x8d, 0x3f, 0x09, 0x70, 0x63, 0x4d, 0xc5, 0xa7, 0x01,
	0xa9, 0xcb, 0x2d, 0x43, 0x36, 0xd5, 0xc7, 0x8f, 0xd8, 0x64, 0x84, 0x87, 0x19, 0x49, 0xa5, 0xab,
	0x5a, 0x47, 0x36, 0x17, 0xbc, 0x1c, 0x76, 0xbd, 0xbe, 0xac, 0xf7, 0x14, 0xc3, 0x44, 0x25, 0xc4,
	0x3c, 0xfe, 0xa8, 0xa3, 0x0c, 0xda, 0xda, 0x50, 0xd6, 0x9f, 0x98, 0x8a, 0x7a, 0xac, 0x89, 0x3b,
	0xf8, 0x23, 0x5d, 0x1e, 0xc8, 0x86, 0xd9, 0xd7, 0xb5, 0xcf, 0x9e, 0x88, 0xbb, 0xa8, 0x95, 0x32,
	0x60, 0x94, 0xd9, 0x6a, 0x1b, 0xca, 0x50, 0x16, 0x0b, 0x14, 0x9e, 0xdf, 0x60, 0x60, 0xb4, 0x8c,
	0xb3, 0x81, 0x58, 0x6c, 0x7c, 0x1f, 0x2a, 0x99, 0x8f, 0x7e, 0xa4, 0x08, 0xf9, 0xa7, 0xed, 0x2e,
	0xeb, 0xae, 0xf1, 0xaf, 0x7b, 0x27, 0x3d, 0x43, 0x14, 0x1a, 0x7f, 0x2b, 0x42, 0xe9, 0xe9, 0x63,
	0xeb, 0x82, 0x7e, 0x5c, 0xd4, 0xa0, 0x1c, 0xd0, 0x99, 0x31, 0x1e, 0x97, 0xab, 0xaf, 0xfb, 0x96,
	0xc7, 0x4f, 0xb1, 0x85, 0x16, 0x9f, 0x0b, 0xf5, 0x05, 0x06, 0x76, 0xa5, 0xd0, 0x99, 0xd1, 0xfc,
	0x89, 0x02, 0x33, 0x74, 0x7c, 0x96, 0x62, 0x65, 0xbd, 0xc2, 0xd9, 0x46, 0x30, 0x70, 0x7c, 0x9b,
	0x3c, 0x82, 0x32, 0xff, 0xf6, 0x99, 0x7c, 0x48, 0x6b, 0x6e, 0x28, 0xb8, 0xcd, 0xbe, 0x96, 0xea,
	0x25, 0x0a, 0x80, 0x7d, 0xfd, 0x53, 0xd8, 0xc1, 0x8c, 0xe0, 0x29, 0xf9, 0xd1, 0x86, 0x38, 0x98,
	0x66, 0x3a, 0x3d, 0x48, 0x0e, 0xa0, 0x30, 0x73, 0xc2, 0xf9, 0x24, 0xa2, 0xed, 0xaa, 0xa4, 0x73,
	0x4a, 0xb2, 0x40, 0x4c, 0x8b, 0xa4, 0xdd, 0xe7, 0x01, 0xe4, 0x51, 0x67, 0x66, 0xac, 0x0f, 0x5e,
	0x2f, 0x2b, 0x1e, 0x4d, 0xf1, 0x04, 0x66, 0x2b, 0xed, 0xbe, 0xf5, 0xdc, 0xad, 0xfc, 0x9d, 0xb2,
	0xce, 0x08, 0xe9, 0xcf, 0x02, 0x54, 0xd9, 0x6f, 0x27, 0x56, 0x18, 0x52, 0x09, 0xa7, 0xb0, 0xc7,
	0x6d, 0x83, 0x2c, 0x2e, 0xe9, 0xf6, 0x37, 0x48, 0xc2, 0x9f, 0x52, 0x59, 0xc0, 0xcc, 0x82, 0x34,
	0xe9, 0x42, 0x91, 0x7f, 0x5b, 0xa6, 0x42, 0x5f, 0xfb, 0xb1, 0x72, 0x9d, 0x8d, 0x51, 0x1d, 0x3d,
	0x86, 0x90, 0x7e, 0x23, 0x40, 0x39, 0xb1, 0x1c, 0xf9, 0x0e, 0xec, 0xc7, 0x9e, 0xf6, 0x2d, 0xde,
	0xa5, 0xca, 0xfa, 0x1e, 0xe7, 0xa9, 0x96, 0xe7, 0x90, 0x9f, 0x67, 0x2f, 0xc2, 0x54, 0xf8, 0x78,
	0x53, 0x15, 0x62, 0x7b, 0xa4, 0x6f, 0x24, 0xfd, 0x41, 0x80, 0xfd, 0xb4, 0x86, 0xa4, 0x05, 0xc5,
	0xcb, 0xe7, 0x5b, 0x19, 0x2a, 0x3e, 0x17, 0x7b, 0x34, 0x77, 0x65, 0x8f, 0x1e, 0x40, 0x21, 0x35,
	0xe5, 0xef, 0xeb, 0x9c, 0x6a, 0x7c, 0x01, 0xb5, 0xa5, 0x14, 0xc1, 0xc9, 0xf5, 0x4c, 0xed, 0xc8,
	0xc7, 0xec, 0x2b, 0xd3, 0x40, 0x56, 0x3b, 0xa2, 0x40, 0xf6, 0xa0, 0xd8, 0xea, 0x74, 0xb0, 0x58,
	0x88, 0x39, 0xac, 0x2a, 0xba, 0x8c, 0xaf, 0x27, 0x4a, 0xe7, 0x91, 0x1e, 0xc8, 0x46, 0x47, 0x3e,
	0x6e, 0x9d, 0x75, 0x0d, 0x71, 0x07, 0x8f, 0x75, 0x95, 0x81, 0x21, 0xee, 0x36, 0x86, 0x00, 0x5d,
	0x77, 0x36, 0xe2, 0xbd, 0xff, 0x00, 0x0a, 0xac, 0x3f, 0x71, 0x0f, 0x70, 0x8a, 0xd4, 0xd3, 0xbe,
	0xc7, 0x8d, 0x98, 0xc4, 0x13, 0xa3, 0xc0, 0x1f, 0xbb, 0xe7, 0x54, 0xed, 0xb2, 0xce, 0xa9, 0xa3,
	0x5f, 0xc3, 0x7b, 0x81, 0xef, 0xf0, 0xfb, 0xbb, 0x01, 0xfb, 0x6f, 0x44, 0x62, 0x84, 0xa3, 0x32,
	0x9a, 0xbc, 0x8f, 0xbc, 0xbe, 0xf0, 0xf4, 0xc7, 0xe7, 0x6e, 0xf4, 0x6c, 0xfe, 0x15, 0x5a, 0xe6,
	0x90, 0x1d, 0xb8, 0xeb, 0x06, 0x87, 0xe7, 0xc1, 0x5d, 0x4e, 0xd0, 0xb3, 0xe1, 0xe1, 0xea, 0xbf,
	0x3c, 0xfe, 0x92, 0x3b, 0xe8, 0x51, 0xa6, 0xa2, 0x35, 0x7b, 0x14, 0x1a, 0x61, 0x9b, 0xc3, 0x7b,
	0x5f, 0x15, 0xe8, 0x99, 0x1f, 0xfc, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x53, 0x83, 0x71, 0xcf, 0x60,
	0x19, 0x00, 0x00,
}
