// Code generated by protoc-gen-go. DO NOT EDIT.
// source: matrix_io/malos/v1/driver.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// configuration of drivers. Both global configuration and
// for specific drivers.
type DriverConfig struct {
	// Delay between updates. In seconds.
	DelayBetweenUpdates float32 `protobuf:"fixed32,1,opt,name=delay_between_updates,json=delayBetweenUpdates,proto3" json:"delay_between_updates,omitempty"`
	// Timeout after last ping.
	TimeoutAfterLastPing float32 `protobuf:"fixed32,2,opt,name=timeout_after_last_ping,json=timeoutAfterLastPing,proto3" json:"timeout_after_last_ping,omitempty"`
	// Values for LEDs. When configuring the driver you should leave
	// delay_between_updates and timeout_after_last_ping unchanged.
	Image *EverloopImage `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// Malos-Eye configuration.
	MalosEyeConfig *MalosEyeConfig `protobuf:"bytes,4,opt,name=malos_eye_config,json=malosEyeConfig,proto3" json:"malos_eye_config,omitempty"`
	// ZigBee Message.
	ZigbeeMessage *ZigBeeMsg `protobuf:"bytes,5,opt,name=zigbee_message,json=zigbeeMessage,proto3" json:"zigbee_message,omitempty"`
	// LIRC service configuration for IR commands.
	Lirc *LircParams `protobuf:"bytes,6,opt,name=lirc,proto3" json:"lirc,omitempty"`
	// ServoMotor service configuration
	Servo *ServoParams `protobuf:"bytes,7,opt,name=servo,proto3" json:"servo,omitempty"`
	// Gpio service configuration
	Gpio *GpioParams `protobuf:"bytes,8,opt,name=gpio,proto3" json:"gpio,omitempty"`
	// Humidity configuration
	Humidity *HumidityParams `protobuf:"bytes,9,opt,name=humidity,proto3" json:"humidity,omitempty"`
	// Microphone Array configuration
	Micarray *MicArrayParams `protobuf:"bytes,10,opt,name=micarray,proto3" json:"micarray,omitempty"`
	//  ZWave message for send commands through the Z/IP Gateway
	Zwave *ZWaveMsg `protobuf:"bytes,11,opt,name=zwave,proto3" json:"zwave,omitempty"`
	// Pocket Sphinx wake word configuration
	Wakeword *WakeWordParams `protobuf:"bytes,12,opt,name=wakeword,proto3" json:"wakeword,omitempty"`
	// Matrix Device parameters
	MatrixDevice         *MatrixDeviceParams `protobuf:"bytes,13,opt,name=matrix_device,json=matrixDevice,proto3" json:"matrix_device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DriverConfig) Reset()         { *m = DriverConfig{} }
func (m *DriverConfig) String() string { return proto.CompactTextString(m) }
func (*DriverConfig) ProtoMessage()    {}
func (*DriverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47624f3190bad3a, []int{0}
}

func (m *DriverConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverConfig.Unmarshal(m, b)
}
func (m *DriverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverConfig.Marshal(b, m, deterministic)
}
func (m *DriverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverConfig.Merge(m, src)
}
func (m *DriverConfig) XXX_Size() int {
	return xxx_messageInfo_DriverConfig.Size(m)
}
func (m *DriverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DriverConfig proto.InternalMessageInfo

func (m *DriverConfig) GetDelayBetweenUpdates() float32 {
	if m != nil {
		return m.DelayBetweenUpdates
	}
	return 0
}

func (m *DriverConfig) GetTimeoutAfterLastPing() float32 {
	if m != nil {
		return m.TimeoutAfterLastPing
	}
	return 0
}

func (m *DriverConfig) GetImage() *EverloopImage {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *DriverConfig) GetMalosEyeConfig() *MalosEyeConfig {
	if m != nil {
		return m.MalosEyeConfig
	}
	return nil
}

func (m *DriverConfig) GetZigbeeMessage() *ZigBeeMsg {
	if m != nil {
		return m.ZigbeeMessage
	}
	return nil
}

func (m *DriverConfig) GetLirc() *LircParams {
	if m != nil {
		return m.Lirc
	}
	return nil
}

func (m *DriverConfig) GetServo() *ServoParams {
	if m != nil {
		return m.Servo
	}
	return nil
}

func (m *DriverConfig) GetGpio() *GpioParams {
	if m != nil {
		return m.Gpio
	}
	return nil
}

func (m *DriverConfig) GetHumidity() *HumidityParams {
	if m != nil {
		return m.Humidity
	}
	return nil
}

func (m *DriverConfig) GetMicarray() *MicArrayParams {
	if m != nil {
		return m.Micarray
	}
	return nil
}

func (m *DriverConfig) GetZwave() *ZWaveMsg {
	if m != nil {
		return m.Zwave
	}
	return nil
}

func (m *DriverConfig) GetWakeword() *WakeWordParams {
	if m != nil {
		return m.Wakeword
	}
	return nil
}

func (m *DriverConfig) GetMatrixDevice() *MatrixDeviceParams {
	if m != nil {
		return m.MatrixDevice
	}
	return nil
}

// Message used by MALOS to report its internal state and the configuration of
// its drivers.
type DriverInfo struct {
	// Driver name.
	DriverName string `protobuf:"bytes,1,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	// Base port: Port where the device is located.
	// base_port => config channel (0MQ pull, you should push)
	// base_port + 1 => keepalive channel (0MQ pull, you should push)
	// base_port + 2 => error channel (0MQ push, you should pull)
	// base_port + 3 => send update channel (0MQ push, you should pull)
	BasePort int32 `protobuf:"varint,2,opt,name=base_port,json=basePort,proto3" json:"base_port,omitempty"`
	// Does the device provide updates? Some devices such as the everloop
	// LED array don't provide updates.
	ProvidesUpdates bool `protobuf:"varint,3,opt,name=provides_updates,json=providesUpdates,proto3" json:"provides_updates,omitempty"`
	// What is the device delay between updates? In milliseconds.
	// This field only makes sense if provides_updates is set.
	DelayBetweenUpdates int32 `protobuf:"varint,4,opt,name=delay_between_updates,json=delayBetweenUpdates,proto3" json:"delay_between_updates,omitempty"`
	// Does the device need pings (keepalive messages) to keep returning messages?
	NeedsPings bool `protobuf:"varint,5,opt,name=needs_pings,json=needsPings,proto3" json:"needs_pings,omitempty"`
	// This field only makes sense if needs_pings is set.
	// If the device hasn't received keepalive messages in a time interenal
	// bigger than this amount, the device will stop sending updates.
	TimeoutAfterLastPing int32 `protobuf:"varint,6,opt,name=timeout_after_last_ping,json=timeoutAfterLastPing,proto3" json:"timeout_after_last_ping,omitempty"`
	// Notes set by the driver. Meant to be read by humans.
	NotesForHuman        string   `protobuf:"bytes,7,opt,name=notes_for_human,json=notesForHuman,proto3" json:"notes_for_human,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriverInfo) Reset()         { *m = DriverInfo{} }
func (m *DriverInfo) String() string { return proto.CompactTextString(m) }
func (*DriverInfo) ProtoMessage()    {}
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47624f3190bad3a, []int{1}
}

func (m *DriverInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverInfo.Unmarshal(m, b)
}
func (m *DriverInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverInfo.Marshal(b, m, deterministic)
}
func (m *DriverInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverInfo.Merge(m, src)
}
func (m *DriverInfo) XXX_Size() int {
	return xxx_messageInfo_DriverInfo.Size(m)
}
func (m *DriverInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DriverInfo proto.InternalMessageInfo

func (m *DriverInfo) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *DriverInfo) GetBasePort() int32 {
	if m != nil {
		return m.BasePort
	}
	return 0
}

func (m *DriverInfo) GetProvidesUpdates() bool {
	if m != nil {
		return m.ProvidesUpdates
	}
	return false
}

func (m *DriverInfo) GetDelayBetweenUpdates() int32 {
	if m != nil {
		return m.DelayBetweenUpdates
	}
	return 0
}

func (m *DriverInfo) GetNeedsPings() bool {
	if m != nil {
		return m.NeedsPings
	}
	return false
}

func (m *DriverInfo) GetTimeoutAfterLastPing() int32 {
	if m != nil {
		return m.TimeoutAfterLastPing
	}
	return 0
}

func (m *DriverInfo) GetNotesForHuman() string {
	if m != nil {
		return m.NotesForHuman
	}
	return ""
}

// Information about all the available drivers.
type MalosDriverInfo struct {
	// The available drivers.
	Info                 []*DriverInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MalosDriverInfo) Reset()         { *m = MalosDriverInfo{} }
func (m *MalosDriverInfo) String() string { return proto.CompactTextString(m) }
func (*MalosDriverInfo) ProtoMessage()    {}
func (*MalosDriverInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d47624f3190bad3a, []int{2}
}

func (m *MalosDriverInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MalosDriverInfo.Unmarshal(m, b)
}
func (m *MalosDriverInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MalosDriverInfo.Marshal(b, m, deterministic)
}
func (m *MalosDriverInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MalosDriverInfo.Merge(m, src)
}
func (m *MalosDriverInfo) XXX_Size() int {
	return xxx_messageInfo_MalosDriverInfo.Size(m)
}
func (m *MalosDriverInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MalosDriverInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MalosDriverInfo proto.InternalMessageInfo

func (m *MalosDriverInfo) GetInfo() []*DriverInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*DriverConfig)(nil), "matrix_io.malos.v1.driver.DriverConfig")
	proto.RegisterType((*DriverInfo)(nil), "matrix_io.malos.v1.driver.DriverInfo")
	proto.RegisterType((*MalosDriverInfo)(nil), "matrix_io.malos.v1.driver.MalosDriverInfo")
}

func init() { proto.RegisterFile("matrix_io/malos/v1/driver.proto", fileDescriptor_d47624f3190bad3a) }

var fileDescriptor_d47624f3190bad3a = []byte{
	// 705 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x5f, 0x4f, 0xdb, 0x3a,
	0x18, 0xc6, 0xd5, 0xd2, 0xf6, 0xb4, 0x2e, 0x05, 0xe4, 0x73, 0x8e, 0x96, 0x81, 0x36, 0xa0, 0xfb,
	0x23, 0xd0, 0x44, 0x2a, 0x98, 0x10, 0x6c, 0x77, 0x74, 0xb0, 0x51, 0x89, 0xb2, 0x2a, 0x13, 0x43,
	0xe2, 0x26, 0x72, 0x9b, 0xb7, 0xc1, 0xa2, 0x8e, 0x23, 0x3b, 0x4d, 0x57, 0xee, 0xf6, 0x71, 0xb6,
	0x0f, 0xb4, 0xcf, 0x33, 0xe5, 0x75, 0xd2, 0x31, 0x29, 0xe1, 0xce, 0x79, 0xdf, 0xe7, 0xf7, 0xf8,
	0x4f, 0xfc, 0x98, 0x6c, 0x0a, 0x16, 0x29, 0xfe, 0xcd, 0xe5, 0xb2, 0x23, 0xd8, 0x44, 0xea, 0x4e,
	0xbc, 0xdf, 0xf1, 0x14, 0x8f, 0x41, 0xd9, 0xa1, 0x92, 0x91, 0xa4, 0x4f, 0x17, 0x02, 0x1b, 0x05,
	0x76, 0xbc, 0x6f, 0x1b, 0xc1, 0xfa, 0xb3, 0x1c, 0x76, 0x24, 0x85, 0x30, 0xe4, 0xfa, 0x46, 0x4e,
	0x9b, 0xcb, 0xb4, 0xb9, 0x9d, 0xd3, 0xc4, 0x01, 0xcc, 0x21, 0x95, 0x3c, 0xcf, 0x91, 0x68, 0x08,
	0x74, 0xda, 0x6f, 0xff, 0xaa, 0x91, 0xe5, 0x53, 0x5c, 0xc9, 0x07, 0x19, 0x8c, 0xb9, 0x4f, 0x0f,
	0xc8, 0xff, 0x1e, 0x4c, 0xd8, 0xdc, 0x1d, 0x42, 0x34, 0x03, 0x08, 0xdc, 0x69, 0xe8, 0xb1, 0x08,
	0xb4, 0x55, 0xda, 0x2a, 0xed, 0x94, 0x9d, 0x7f, 0xb1, 0xd9, 0x35, 0xbd, 0x2b, 0xd3, 0xa2, 0x87,
	0xe4, 0x49, 0xc4, 0x05, 0xc8, 0x69, 0xe4, 0xb2, 0x71, 0x04, 0xca, 0x9d, 0x30, 0x1d, 0xb9, 0x21,
	0x0f, 0x7c, 0xab, 0x8c, 0xd4, 0x7f, 0x69, 0xfb, 0x24, 0xe9, 0x5e, 0x30, 0x1d, 0x0d, 0x78, 0xe0,
	0xd3, 0xf7, 0xa4, 0xca, 0x05, 0xf3, 0xc1, 0x5a, 0xda, 0x2a, 0xed, 0x34, 0x0f, 0x5e, 0xda, 0x39,
	0xa7, 0xc4, 0xa5, 0x7d, 0x16, 0x83, 0x9a, 0x48, 0x19, 0xf6, 0x12, 0xad, 0x63, 0x10, 0x7a, 0x45,
	0xd6, 0x50, 0xe3, 0xc2, 0x1c, 0xdc, 0x11, 0x2e, 0xdd, 0xaa, 0xa0, 0xcd, 0x9b, 0x3c, 0x9b, 0xc5,
	0xa9, 0xf4, 0x93, 0xc1, 0xd9, 0x1c, 0xcc, 0x6e, 0x9d, 0x15, 0xf1, 0xd7, 0x37, 0xed, 0x91, 0x95,
	0x7b, 0xee, 0x0f, 0x01, 0x5c, 0x01, 0x5a, 0x27, 0x6b, 0xab, 0xa2, 0x69, 0x3b, 0xcf, 0x14, 0x7f,
	0xd3, 0x0d, 0xf7, 0xbb, 0x00, 0x7d, 0xed, 0x3b, 0x2d, 0x43, 0xf6, 0x0d, 0x48, 0x8f, 0x48, 0x65,
	0xc2, 0xd5, 0xc8, 0xaa, 0xa1, 0xc1, 0x8b, 0x42, 0x83, 0x0b, 0xae, 0x46, 0x03, 0xa6, 0x98, 0xd0,
	0x0e, 0x02, 0xf4, 0x98, 0x54, 0x35, 0xa8, 0x58, 0x5a, 0xff, 0x14, 0x4f, 0xcd, 0xa5, 0xfd, 0x25,
	0xd1, 0xa4, 0xa0, 0x01, 0xe8, 0x21, 0xa9, 0xf8, 0x21, 0x97, 0x56, 0x1d, 0xc1, 0xed, 0x02, 0xf0,
	0x53, 0xc8, 0x33, 0x0e, 0xe5, 0xf4, 0x94, 0xd4, 0x6f, 0xa7, 0x82, 0x7b, 0x3c, 0x9a, 0x5b, 0x0d,
	0x44, 0x77, 0xf2, 0x50, 0x73, 0x6d, 0xce, 0x53, 0x65, 0xea, 0xb0, 0x20, 0xe9, 0x09, 0xa9, 0x0b,
	0x3e, 0x62, 0x4a, 0xb1, 0xb9, 0x45, 0xd0, 0xe5, 0x55, 0xc1, 0x02, 0xfa, 0x7c, 0x74, 0x92, 0xc8,
	0x32, 0x8b, 0x0c, 0xa3, 0x47, 0xa4, 0x7a, 0x3f, 0x63, 0x31, 0x58, 0xcd, 0xe2, 0x0d, 0x98, 0x43,
	0xbf, 0x66, 0x31, 0x9e, 0xb9, 0xd1, 0x27, 0x73, 0xcf, 0xd8, 0x1d, 0xcc, 0xa4, 0xf2, 0xac, 0xe5,
	0x47, 0xe7, 0xbe, 0x66, 0x77, 0x70, 0x2d, 0x95, 0x97, 0xcd, 0x9d, 0x61, 0xf4, 0x92, 0xb4, 0x52,
	0xc2, 0x83, 0x98, 0x8f, 0xc0, 0x6a, 0xa1, 0xcf, 0x6e, 0xd1, 0x1e, 0xb0, 0x7a, 0x8a, 0xd2, 0xd4,
	0x6b, 0x59, 0x3c, 0xa8, 0xb5, 0x7f, 0x94, 0x09, 0x31, 0xc1, 0xea, 0x05, 0x63, 0x49, 0x37, 0x49,
	0xd3, 0x04, 0xde, 0x0d, 0x98, 0x00, 0x0c, 0x53, 0xc3, 0x21, 0xa6, 0x74, 0xc9, 0x04, 0xd0, 0x0d,
	0xd2, 0x18, 0x32, 0x0d, 0x6e, 0x28, 0x55, 0x84, 0xa9, 0xa9, 0x3a, 0xf5, 0xa4, 0x30, 0x90, 0x2a,
	0xa2, 0xbb, 0x64, 0x2d, 0x54, 0x32, 0xe6, 0x1e, 0xe8, 0x45, 0x1e, 0x93, 0xd0, 0xd4, 0x9d, 0xd5,
	0xac, 0x9e, 0x65, 0xb1, 0x30, 0xbf, 0x15, 0xf4, 0xcc, 0xcd, 0xef, 0x26, 0x69, 0x06, 0x00, 0x9e,
	0xc6, 0xc8, 0x6a, 0xbc, 0xf2, 0x75, 0x87, 0x60, 0x29, 0x09, 0xea, 0xa3, 0x01, 0xaf, 0xa1, 0x6d,
	0x7e, 0xc0, 0x5f, 0x93, 0xd5, 0x40, 0x46, 0xa0, 0xdd, 0xb1, 0x54, 0xee, 0xed, 0x54, 0xb0, 0x00,
	0xef, 0x74, 0xc3, 0x69, 0x61, 0xf9, 0xa3, 0x54, 0xe7, 0x49, 0xb1, 0x7d, 0x41, 0x56, 0x31, 0x97,
	0x0f, 0xce, 0xeb, 0x1d, 0xa9, 0xf0, 0x60, 0x2c, 0xad, 0xd2, 0xd6, 0x52, 0xd1, 0xdf, 0x4c, 0x5f,
	0xd8, 0x3f, 0x90, 0x83, 0x48, 0xf7, 0x7b, 0x89, 0x6c, 0xc8, 0x00, 0x52, 0x24, 0x7b, 0x2c, 0x17,
	0x5c, 0xb7, 0x69, 0x88, 0x41, 0x52, 0x1d, 0x94, 0x6e, 0x8e, 0x7d, 0x1e, 0xdd, 0x4e, 0x87, 0xc9,
	0xc5, 0xea, 0x18, 0x64, 0x0f, 0x1f, 0x4b, 0x1c, 0x21, 0xaa, 0xf7, 0xfc, 0xac, 0xf0, 0xf0, 0x1d,
	0xfd, 0x59, 0xb6, 0xcc, 0x2d, 0xe8, 0x7d, 0x36, 0xcf, 0x4a, 0xba, 0x14, 0xfb, 0xeb, 0xfe, 0xb0,
	0x86, 0xe0, 0xdb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x77, 0x9f, 0x6d, 0x47, 0x1a, 0x06, 0x00,
	0x00,
}
